import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { SKILL_TAGS, skillNeedles, skillTagLabel } from "../../lib/skill-tags"

const dir = dirname(fileURLToPath(import.meta.url))

function esc(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'")
}

function rxEscape(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

const needles = skillNeedles()
const structs = needles.map((n) => {
  const label = esc(skillTagLabel(n.id, "en"))
  return `  STRUCT('${esc(n.id)}' AS id, '${label}' AS label, '${esc(n.needle)}' AS needle, ${n.boundary ? "TRUE" : "FALSE"} AS boundary, r'${rxEscape(n.needle)}' AS rx)`
})

const labels = SKILL_TAGS.map(
  (s) => `  STRUCT('${esc(s.id)}' AS id, '${esc(s.label.en)}' AS label)`,
)

const sql = `-- Generated by scripts/bq/gen_skill_tags.ts — original-text skill tags.

CREATE TEMP FUNCTION fold(s STRING) AS (
  REGEXP_REPLACE(NORMALIZE(LOWER(IFNULL(s, "")), NFD), r'\\p{M}', '')
);
CREATE TEMP FUNCTION strip_html(s STRING) AS (
  REGEXP_REPLACE(IFNULL(s, ""), r'<[^>]+>', ' ')
);
CREATE TEMP FUNCTION hay(title STRING, excerpt STRING, body STRING) AS (
  fold(CONCAT(
    ' ',
    strip_html(title), ' ',
    strip_html(excerpt), ' ',
    strip_html(body), ' '
  ))
);

CREATE OR REPLACE TABLE \`poetic-sentinel-402405.apply_jobs_jobs2_prod.skill_needles\` AS
SELECT * FROM UNNEST([
${structs.join(",\n")}
]);

CREATE OR REPLACE TABLE \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offer_skills\`
CLUSTER BY job_key, skill_id AS
WITH jobs AS (
  SELECT
    j.job_key,
    hay(j.title, j.description_excerpt, d.description) AS hay
  FROM \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country\` j
  LEFT JOIN \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_descriptions\` d
    USING (job_key)
)
SELECT
  job_key,
  skill_id,
  skill_label,
  evidence,
  source
FROM (
  SELECT
    job_key,
    skill_id,
    skill_label,
    evidence,
    source,
    ROW_NUMBER() OVER (PARTITION BY job_key, skill_id ORDER BY source, evidence) AS rn
  FROM (
    SELECT
      j.job_key,
      n.id AS skill_id,
      n.label AS skill_label,
      n.needle AS evidence,
      'description' AS source
    FROM jobs j
    JOIN \`poetic-sentinel-402405.apply_jobs_jobs2_prod.skill_needles\` n
      ON IF(
        n.boundary,
        REGEXP_CONTAINS(j.hay, CONCAT(r'(^|[^a-z0-9+.#])', n.rx, r'([^a-z0-9+.#]|$)')),
        STRPOS(j.hay, n.needle) > 0
      )

    UNION ALL

    SELECT
      jo.job_key,
      n.id AS skill_id,
      n.label AS skill_label,
      fold(h.skill) AS evidence,
      'harvest' AS source
    FROM \`poetic-sentinel-402405.apply_jobs.job_skills\` h
    JOIN \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country\` jo
      ON jo.url_norm = \`poetic-sentinel-402405.apply_jobs_jobs2_prod.url_norm\`(h.url)
    JOIN \`poetic-sentinel-402405.apply_jobs_jobs2_prod.skill_needles\` n
      ON fold(h.skill) = n.needle OR fold(h.skill) = n.id
  )
)
WHERE rn = 1
QUALIFY ROW_NUMBER() OVER (PARTITION BY job_key ORDER BY source, skill_id) <= 16;

CREATE OR REPLACE TABLE \`poetic-sentinel-402405.apply_jobs_jobs2_dev.skill_needles\`
AS SELECT * FROM \`poetic-sentinel-402405.apply_jobs_jobs2_prod.skill_needles\`;

CREATE OR REPLACE TABLE \`poetic-sentinel-402405.apply_jobs_jobs2_dev.job_offer_skills\`
CLUSTER BY job_key, skill_id AS
SELECT * FROM \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offer_skills\`;
`

writeFileSync(join(dir, "patch_skills.sql"), sql)
console.log("wrote patch_skills.sql needles", needles.length, "skills", SKILL_TAGS.length, "labels", labels.length)
