import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { specialtyNeedles } from "../../lib/skills-catalog"
import { CITIES, NL_NUTS } from "../../lib/location"

const dir = dirname(fileURLToPath(import.meta.url))

function esc(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'")
}

const needles = specialtyNeedles()
const seen = new Set<string>()
const structs: string[] = []
for (const n of needles) {
  const needle = n.needle.trim()
  if (needle.length < 3) continue
  const key = `${n.id}\t${needle}`
  if (seen.has(key)) continue
  seen.add(key)
  structs.push(`  STRUCT('${esc(n.id)}' AS id, '${esc(needle)}' AS needle)`)
}

const specSql = `-- Generated by scripts/bq/gen_patches.ts — occupation needles + last-resort category.

CREATE TEMP FUNCTION fold(s STRING) AS (
  REGEXP_REPLACE(NORMALIZE(LOWER(IFNULL(s, "")), NFD), r'\\p{M}', '')
);

CREATE OR REPLACE TABLE \`poetic-sentinel-402405.apply_jobs_jobs2_prod.specialty_needles\` AS
SELECT * FROM UNNEST([
${structs.join(",\n")}
]);

CREATE OR REPLACE TABLE \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp\`
CLUSTER BY country_iso2, public_rank AS
SELECT
  j.* EXCEPT (specialties),
  IFNULL(
    s.specialties,
    IF(TRIM(IFNULL(j.title, '')) = '', ['weitere'], ['general'])
  ) AS specialties
FROM \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country\` j
LEFT JOIN (
  SELECT
    j2.job_key,
    ARRAY_AGG(DISTINCT n.id) AS specialties
  FROM \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country\` j2
  JOIN \`poetic-sentinel-402405.apply_jobs_jobs2_prod.specialty_needles\` n
    ON STRPOS(
      fold(CONCAT(' ', IFNULL(j2.title, ''), ' ', IFNULL(j2.description_excerpt, ''), ' ')),
      fold(n.needle)
    ) > 0
  GROUP BY j2.job_key
) s USING (job_key);

CREATE OR REPLACE TABLE \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country\`
CLUSTER BY country_iso2, public_rank AS
SELECT * FROM \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp\`;

DROP TABLE \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp\`;
`

const cityStructs = CITIES.map((c) => `  '${esc(c)}'`).join(",\n")
const nutsStructs = Object.entries(NL_NUTS)
  .map(([k, v]) => `  STRUCT('${esc(k)}' AS prefix, '${esc(v)}' AS label)`)
  .join(",\n")

const locSql = `-- Generated by scripts/bq/gen_patches.ts — headquarters + recovered job location.

CREATE TEMP FUNCTION fold(s STRING) AS (
  REGEXP_REPLACE(NORMALIZE(LOWER(IFNULL(s, "")), NFD), r'\\p{M}', '')
);

CREATE TEMP FUNCTION is_generic_loc(s STRING) AS (
  fold(s) IN (
    '', 'default', 'unknown', 'n/a', 'na', 'none', 'null', '-', '.',
    'eu (other)', 'europe', 'worldwide', 'global',
    'germany', 'de', 'deutschland', 'czechia', 'cz', 'czech republic',
    'netherlands', 'nl', 'holland', 'france', 'fr', 'united kingdom', 'gb', 'uk',
    'united states', 'us', 'usa', 'austria', 'at', 'switzerland', 'ch',
    'belgium', 'be', 'poland', 'pl', 'spain', 'es', 'italy', 'it', 'sweden', 'se',
    'singapore', 'sg', 'ireland', 'ie', 'denmark', 'dk', 'norway', 'no', 'finland', 'fi',
    'luxembourg', 'lu', 'croatia', 'hr', 'slovakia', 'sk', 'romania', 'ro', 'slovenia', 'si',
    'malta', 'mt', 'latvia', 'lv', 'estonia', 'ee', 'lithuania', 'lt', 'hungary', 'hu',
    'portugal', 'pt', 'greece', 'gr', 'japan', 'jp', 'canada', 'ca', 'australia', 'au',
    'india', 'in', 'china', 'cn', 'brazil', 'br', 'mexico', 'mx'
  )
  OR REGEXP_CONTAINS(fold(s), r'^[a-z]{2}$')
  OR REGEXP_CONTAINS(fold(s), r'^nl[0-9a-z]{2,3}(,| |$)')
  OR STARTS_WITH(fold(s), 'obec/')
);

CREATE OR REPLACE TABLE \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp\`
CLUSTER BY country_iso2, public_rank AS
WITH cities AS (
  SELECT city, fold(city) AS f
  FROM UNNEST([
${cityStructs}
  ]) AS city
),
nuts AS (
  SELECT * FROM UNNEST([
${nutsStructs}
  ])
),
titled AS (
  SELECT
    j.job_key,
    ARRAY_AGG(c.city ORDER BY LENGTH(c.f) DESC LIMIT 1)[SAFE_OFFSET(0)] AS title_city
  FROM \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country\` j
  JOIN cities c
    ON STRPOS(CONCAT(' ', fold(CONCAT(IFNULL(j.title, ''), ' ', IFNULL(j.company, ''))), ' '), CONCAT(' ', c.f, ' ')) > 0
  GROUP BY j.job_key
),
posted AS (
  SELECT
    j.job_key,
    ARRAY_AGG(c.city ORDER BY LENGTH(c.f) DESC LIMIT 1)[SAFE_OFFSET(0)] AS loc_city
  FROM \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country\` j
  JOIN cities c
    ON STRPOS(CONCAT(' ', fold(IFNULL(j.job_location, '')), ' '), CONCAT(' ', c.f, ' ')) > 0
  GROUP BY j.job_key
),
company_hq AS (
  SELECT company, city FROM (
    SELECT
      j.company,
      COALESCE(t.title_city, p.loc_city) AS city,
      COUNT(*) AS n
    FROM \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country\` j
    LEFT JOIN titled t USING (job_key)
    LEFT JOIN posted p USING (job_key)
    WHERE COALESCE(t.title_city, p.loc_city) IS NOT NULL
      AND IFNULL(j.company, '') != ''
    GROUP BY 1, 2
  )
  QUALIFY ROW_NUMBER() OVER (PARTITION BY company ORDER BY n DESC) = 1
)
SELECT
  j.* EXCEPT (job_location, headquarters_location),
  CASE
    WHEN REGEXP_CONTAINS(LOWER(CONCAT(IFNULL(j.is_remote, ''), ' ', IFNULL(j.title, ''))), r'remote|homeoffice|home office|hybrid')
         AND t.title_city IS NULL
         AND is_generic_loc(j.job_location)
      THEN j.job_location
    WHEN t.title_city IS NOT NULL THEN t.title_city
    WHEN REGEXP_CONTAINS(fold(IFNULL(j.job_location, '')), r'\\bnl[0-9]{2}') THEN
      (SELECT label FROM nuts n
       WHERE STARTS_WITH(REGEXP_EXTRACT(fold(j.job_location), r'nl[0-9]{2}'), n.prefix)
       LIMIT 1)
    WHEN p.loc_city IS NOT NULL THEN p.loc_city
    WHEN is_generic_loc(j.job_location) THEN COALESCE(ch.city, h.country_name, j.job_location)
    ELSE j.job_location
  END AS job_location,
  COALESCE(
    ch.city,
    t.title_city,
    p.loc_city,
    IF(is_generic_loc(j.headquarters_location), NULL, j.headquarters_location),
    h.country_name,
    j.headquarters_location
  ) AS headquarters_location
FROM \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country\` j
LEFT JOIN titled t USING (job_key)
LEFT JOIN posted p USING (job_key)
LEFT JOIN company_hq ch ON ch.company = j.company
LEFT JOIN (
  SELECT iso2, name AS country_name FROM UNNEST([
    STRUCT('DE' AS iso2, 'Germany' AS name), STRUCT('NL','Netherlands'), STRUCT('CZ','Czechia'),
    STRUCT('GB','United Kingdom'), STRUCT('US','United States'), STRUCT('FR','France'),
    STRUCT('AT','Austria'), STRUCT('CH','Switzerland'), STRUCT('BE','Belgium'),
    STRUCT('PL','Poland'), STRUCT('SE','Sweden'), STRUCT('SG','Singapore'),
    STRUCT('ES','Spain'), STRUCT('IT','Italy'), STRUCT('IE','Ireland'),
    STRUCT('DK','Denmark'), STRUCT('NO','Norway'), STRUCT('FI','Finland'),
    STRUCT('LU','Luxembourg'), STRUCT('SK','Slovakia'), STRUCT('RO','Romania'),
    STRUCT('HR','Croatia'), STRUCT('MT','Malta'), STRUCT('SI','Slovenia'),
    STRUCT('LV','Latvia'), STRUCT('EE','Estonia'), STRUCT('CA','Canada'),
    STRUCT('PT','Portugal'), STRUCT('LT','Lithuania'), STRUCT('CY','Cyprus'),
    STRUCT('BG','Bulgaria'), STRUCT('HU','Hungary'), STRUCT('JP','Japan'),
    STRUCT('GR','Greece'), STRUCT('AU','Australia'), STRUCT('AE','UAE'),
    STRUCT('IS','Iceland'), STRUCT('BR','Brazil'), STRUCT('CN','China'),
    STRUCT('MX','Mexico'), STRUCT('IN','India'), STRUCT('KR','South Korea'),
    STRUCT('IL','Israel'), STRUCT('ZZ','Unknown')
  ])
) h ON h.iso2 = j.country_iso2;

CREATE OR REPLACE TABLE \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country\`
CLUSTER BY country_iso2, public_rank AS
SELECT * FROM \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp\`;

DROP TABLE \`poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp\`;
`

writeFileSync(join(dir, "patch_specialties.sql"), specSql)
writeFileSync(join(dir, "patch_locations.sql"), locSql)
console.log(`needles ${structs.length} cities ${CITIES.length}`)
