-- Generated by scripts/bq/gen_skill_tags.ts — original-text skill tags.

CREATE TEMP FUNCTION fold(s STRING) AS (
  REGEXP_REPLACE(NORMALIZE(LOWER(IFNULL(s, "")), NFD), r'\p{M}', '')
);
CREATE TEMP FUNCTION strip_html(s STRING) AS (
  REGEXP_REPLACE(IFNULL(s, ""), r'<[^>]+>', ' ')
);
CREATE TEMP FUNCTION hay(title STRING, excerpt STRING, body STRING) AS (
  fold(CONCAT(
    ' ',
    strip_html(title), ' ',
    strip_html(excerpt), ' ',
    strip_html(body), ' '
  ))
);

CREATE OR REPLACE TABLE `poetic-sentinel-402405.apply_jobs_jobs2_prod.skill_needles` AS
SELECT * FROM UNNEST([
  STRUCT('java' AS id, 'Java' AS label, 'spring framework' AS needle, FALSE AS boundary, r'spring framework' AS rx),
  STRUCT('java' AS id, 'Java' AS label, 'spring boot' AS needle, FALSE AS boundary, r'spring boot' AS rx),
  STRUCT('java' AS id, 'Java' AS label, 'jakarta ee' AS needle, FALSE AS boundary, r'jakarta ee' AS rx),
  STRUCT('java' AS id, 'Java' AS label, 'java' AS needle, TRUE AS boundary, r'java' AS rx),
  STRUCT('java' AS id, 'Java' AS label, 'j2ee' AS needle, TRUE AS boundary, r'j2ee' AS rx),
  STRUCT('python' AS id, 'Python' AS label, 'fastapi' AS needle, FALSE AS boundary, r'fastapi' AS rx),
  STRUCT('python' AS id, 'Python' AS label, 'python' AS needle, FALSE AS boundary, r'python' AS rx),
  STRUCT('python' AS id, 'Python' AS label, 'django' AS needle, FALSE AS boundary, r'django' AS rx),
  STRUCT('python' AS id, 'Python' AS label, 'pandas' AS needle, FALSE AS boundary, r'pandas' AS rx),
  STRUCT('python' AS id, 'Python' AS label, 'flask' AS needle, FALSE AS boundary, r'flask' AS rx),
  STRUCT('javascript' AS id, 'JavaScript' AS label, 'javascript' AS needle, FALSE AS boundary, r'javascript' AS rx),
  STRUCT('javascript' AS id, 'JavaScript' AS label, 'node.js' AS needle, FALSE AS boundary, r'node\.js' AS rx),
  STRUCT('javascript' AS id, 'JavaScript' AS label, 'node js' AS needle, FALSE AS boundary, r'node js' AS rx),
  STRUCT('javascript' AS id, 'JavaScript' AS label, 'nodejs' AS needle, FALSE AS boundary, r'nodejs' AS rx),
  STRUCT('typescript' AS id, 'TypeScript' AS label, 'typescript' AS needle, FALSE AS boundary, r'typescript' AS rx),
  STRUCT('csharp' AS id, 'C#' AS label, 'asp.net' AS needle, FALSE AS boundary, r'asp\.net' AS rx),
  STRUCT('csharp' AS id, 'C#' AS label, 'csharp' AS needle, FALSE AS boundary, r'csharp' AS rx),
  STRUCT('csharp' AS id, 'C#' AS label, 'dotnet' AS needle, FALSE AS boundary, r'dotnet' AS rx),
  STRUCT('csharp' AS id, 'C#' AS label, '.net' AS needle, TRUE AS boundary, r'\.net' AS rx),
  STRUCT('csharp' AS id, 'C#' AS label, 'c#' AS needle, TRUE AS boundary, r'c#' AS rx),
  STRUCT('cpp' AS id, 'C++' AS label, 'cplusplus' AS needle, FALSE AS boundary, r'cplusplus' AS rx),
  STRUCT('cpp' AS id, 'C++' AS label, 'c++' AS needle, TRUE AS boundary, r'c\+\+' AS rx),
  STRUCT('golang' AS id, 'Go' AS label, 'go lang' AS needle, FALSE AS boundary, r'go lang' AS rx),
  STRUCT('golang' AS id, 'Go' AS label, 'golang' AS needle, FALSE AS boundary, r'golang' AS rx),
  STRUCT('kotlin' AS id, 'Kotlin' AS label, 'kotlin' AS needle, FALSE AS boundary, r'kotlin' AS rx),
  STRUCT('rust' AS id, 'Rust' AS label, 'rust developer' AS needle, FALSE AS boundary, r'rust developer' AS rx),
  STRUCT('rust' AS id, 'Rust' AS label, 'rust engineer' AS needle, FALSE AS boundary, r'rust engineer' AS rx),
  STRUCT('rust' AS id, 'Rust' AS label, 'rust lang' AS needle, FALSE AS boundary, r'rust lang' AS rx),
  STRUCT('rust' AS id, 'Rust' AS label, '(rust)' AS needle, FALSE AS boundary, r'\(rust\)' AS rx),
  STRUCT('php' AS id, 'PHP' AS label, 'laravel' AS needle, FALSE AS boundary, r'laravel' AS rx),
  STRUCT('php' AS id, 'PHP' AS label, 'symfony' AS needle, FALSE AS boundary, r'symfony' AS rx),
  STRUCT('php' AS id, 'PHP' AS label, 'php' AS needle, TRUE AS boundary, r'php' AS rx),
  STRUCT('ruby' AS id, 'Ruby' AS label, 'ruby on rails' AS needle, FALSE AS boundary, r'ruby on rails' AS rx),
  STRUCT('ruby' AS id, 'Ruby' AS label, 'ruby' AS needle, TRUE AS boundary, r'ruby' AS rx),
  STRUCT('swift' AS id, 'Swift' AS label, 'swiftui' AS needle, FALSE AS boundary, r'swiftui' AS rx),
  STRUCT('swift' AS id, 'Swift' AS label, 'swift' AS needle, TRUE AS boundary, r'swift' AS rx),
  STRUCT('sql' AS id, 'SQL' AS label, 'postgresql' AS needle, FALSE AS boundary, r'postgresql' AS rx),
  STRUCT('sql' AS id, 'SQL' AS label, 'postgres' AS needle, FALSE AS boundary, r'postgres' AS rx),
  STRUCT('sql' AS id, 'SQL' AS label, 'mysql' AS needle, FALSE AS boundary, r'mysql' AS rx),
  STRUCT('sql' AS id, 'SQL' AS label, 't-sql' AS needle, FALSE AS boundary, r't-sql' AS rx),
  STRUCT('sql' AS id, 'SQL' AS label, 'sql' AS needle, TRUE AS boundary, r'sql' AS rx),
  STRUCT('react' AS id, 'React' AS label, 'react.js' AS needle, FALSE AS boundary, r'react\.js' AS rx),
  STRUCT('react' AS id, 'React' AS label, 'reactjs' AS needle, FALSE AS boundary, r'reactjs' AS rx),
  STRUCT('react' AS id, 'React' AS label, 'react' AS needle, TRUE AS boundary, r'react' AS rx),
  STRUCT('angular' AS id, 'Angular' AS label, 'angular' AS needle, TRUE AS boundary, r'angular' AS rx),
  STRUCT('vue' AS id, 'Vue' AS label, 'vue.js' AS needle, FALSE AS boundary, r'vue\.js' AS rx),
  STRUCT('vue' AS id, 'Vue' AS label, 'vue js' AS needle, FALSE AS boundary, r'vue js' AS rx),
  STRUCT('vue' AS id, 'Vue' AS label, 'vuejs' AS needle, FALSE AS boundary, r'vuejs' AS rx),
  STRUCT('spring' AS id, 'Spring' AS label, 'spring framework' AS needle, FALSE AS boundary, r'spring framework' AS rx),
  STRUCT('spring' AS id, 'Spring' AS label, 'spring boot' AS needle, FALSE AS boundary, r'spring boot' AS rx),
  STRUCT('kafka' AS id, 'Kafka' AS label, 'kafka' AS needle, TRUE AS boundary, r'kafka' AS rx),
  STRUCT('spark' AS id, 'Spark' AS label, 'apache spark' AS needle, FALSE AS boundary, r'apache spark' AS rx),
  STRUCT('spark' AS id, 'Spark' AS label, 'pyspark' AS needle, FALSE AS boundary, r'pyspark' AS rx),
  STRUCT('spark' AS id, 'Spark' AS label, 'spark' AS needle, TRUE AS boundary, r'spark' AS rx),
  STRUCT('airflow' AS id, 'Airflow' AS label, 'airflow' AS needle, FALSE AS boundary, r'airflow' AS rx),
  STRUCT('kubernetes' AS id, 'Kubernetes' AS label, 'kubernetes' AS needle, FALSE AS boundary, r'kubernetes' AS rx),
  STRUCT('kubernetes' AS id, 'Kubernetes' AS label, 'k8s' AS needle, TRUE AS boundary, r'k8s' AS rx),
  STRUCT('docker' AS id, 'Docker' AS label, 'docker' AS needle, TRUE AS boundary, r'docker' AS rx),
  STRUCT('terraform' AS id, 'Terraform' AS label, 'terraform' AS needle, FALSE AS boundary, r'terraform' AS rx),
  STRUCT('linux' AS id, 'Linux' AS label, 'ubuntu' AS needle, FALSE AS boundary, r'ubuntu' AS rx),
  STRUCT('linux' AS id, 'Linux' AS label, 'linux' AS needle, TRUE AS boundary, r'linux' AS rx),
  STRUCT('linux' AS id, 'Linux' AS label, 'rhel' AS needle, TRUE AS boundary, r'rhel' AS rx),
  STRUCT('aws' AS id, 'AWS' AS label, 'amazon web services' AS needle, FALSE AS boundary, r'amazon web services' AS rx),
  STRUCT('aws' AS id, 'AWS' AS label, 'aws' AS needle, TRUE AS boundary, r'aws' AS rx),
  STRUCT('azure' AS id, 'Azure' AS label, 'microsoft azure' AS needle, FALSE AS boundary, r'microsoft azure' AS rx),
  STRUCT('azure' AS id, 'Azure' AS label, 'azure' AS needle, FALSE AS boundary, r'azure' AS rx),
  STRUCT('gcp' AS id, 'GCP' AS label, 'google cloud' AS needle, FALSE AS boundary, r'google cloud' AS rx),
  STRUCT('gcp' AS id, 'GCP' AS label, 'gcp' AS needle, TRUE AS boundary, r'gcp' AS rx),
  STRUCT('sap' AS id, 'SAP' AS label, 's/4hana' AS needle, FALSE AS boundary, r's/4hana' AS rx),
  STRUCT('sap' AS id, 'SAP' AS label, 's4hana' AS needle, FALSE AS boundary, r's4hana' AS rx),
  STRUCT('sap' AS id, 'SAP' AS label, 'sap' AS needle, TRUE AS boundary, r'sap' AS rx),
  STRUCT('abap' AS id, 'ABAP' AS label, 'abap' AS needle, TRUE AS boundary, r'abap' AS rx),
  STRUCT('sap_mm' AS id, 'SAP MM' AS label, 'sap mm' AS needle, FALSE AS boundary, r'sap mm' AS rx),
  STRUCT('sap_sd' AS id, 'SAP SD' AS label, 'sap sd' AS needle, FALSE AS boundary, r'sap sd' AS rx),
  STRUCT('salesforce' AS id, 'Salesforce' AS label, 'salesforce' AS needle, FALSE AS boundary, r'salesforce' AS rx),
  STRUCT('servicenow' AS id, 'ServiceNow' AS label, 'servicenow' AS needle, FALSE AS boundary, r'servicenow' AS rx),
  STRUCT('excel' AS id, 'Excel' AS label, 'microsoft excel' AS needle, FALSE AS boundary, r'microsoft excel' AS rx),
  STRUCT('excel' AS id, 'Excel' AS label, 'excel' AS needle, TRUE AS boundary, r'excel' AS rx),
  STRUCT('powerbi' AS id, 'Power BI' AS label, 'power bi' AS needle, FALSE AS boundary, r'power bi' AS rx),
  STRUCT('powerbi' AS id, 'Power BI' AS label, 'powerbi' AS needle, FALSE AS boundary, r'powerbi' AS rx),
  STRUCT('tableau' AS id, 'Tableau' AS label, 'tableau' AS needle, FALSE AS boundary, r'tableau' AS rx),
  STRUCT('snowflake' AS id, 'Snowflake' AS label, 'snowflake' AS needle, FALSE AS boundary, r'snowflake' AS rx),
  STRUCT('databricks' AS id, 'Databricks' AS label, 'databricks' AS needle, FALSE AS boundary, r'databricks' AS rx),
  STRUCT('ml' AS id, 'Machine learning' AS label, 'machine learning' AS needle, FALSE AS boundary, r'machine learning' AS rx),
  STRUCT('ml' AS id, 'Machine learning' AS label, 'deep learning' AS needle, FALSE AS boundary, r'deep learning' AS rx),
  STRUCT('ml' AS id, 'Machine learning' AS label, 'tensorflow' AS needle, FALSE AS boundary, r'tensorflow' AS rx),
  STRUCT('ml' AS id, 'Machine learning' AS label, 'pytorch' AS needle, FALSE AS boundary, r'pytorch' AS rx),
  STRUCT('llm' AS id, 'LLM' AS label, 'large language model' AS needle, FALSE AS boundary, r'large language model' AS rx),
  STRUCT('llm' AS id, 'LLM' AS label, 'generative ai' AS needle, FALSE AS boundary, r'generative ai' AS rx),
  STRUCT('llm' AS id, 'LLM' AS label, 'llm' AS needle, TRUE AS boundary, r'llm' AS rx),
  STRUCT('devops' AS id, 'DevOps' AS label, 'site reliability' AS needle, FALSE AS boundary, r'site reliability' AS rx),
  STRUCT('devops' AS id, 'DevOps' AS label, 'devops' AS needle, FALSE AS boundary, r'devops' AS rx),
  STRUCT('devops' AS id, 'DevOps' AS label, 'ci/cd' AS needle, FALSE AS boundary, r'ci/cd' AS rx),
  STRUCT('devops' AS id, 'DevOps' AS label, 'cicd' AS needle, TRUE AS boundary, r'cicd' AS rx),
  STRUCT('devops' AS id, 'DevOps' AS label, 'sre' AS needle, TRUE AS boundary, r'sre' AS rx),
  STRUCT('cybersecurity' AS id, 'Cybersecurity' AS label, 'information security' AS needle, FALSE AS boundary, r'information security' AS rx),
  STRUCT('cybersecurity' AS id, 'Cybersecurity' AS label, 'cybersecurity' AS needle, FALSE AS boundary, r'cybersecurity' AS rx),
  STRUCT('cybersecurity' AS id, 'Cybersecurity' AS label, 'infosec' AS needle, FALSE AS boundary, r'infosec' AS rx),
  STRUCT('cybersecurity' AS id, 'Cybersecurity' AS label, 'appsec' AS needle, FALSE AS boundary, r'appsec' AS rx),
  STRUCT('embedded' AS id, 'Embedded' AS label, 'microcontroller' AS needle, FALSE AS boundary, r'microcontroller' AS rx),
  STRUCT('embedded' AS id, 'Embedded' AS label, 'embedded' AS needle, FALSE AS boundary, r'embedded' AS rx),
  STRUCT('embedded' AS id, 'Embedded' AS label, 'firmware' AS needle, FALSE AS boundary, r'firmware' AS rx),
  STRUCT('embedded' AS id, 'Embedded' AS label, 'rtos' AS needle, TRUE AS boundary, r'rtos' AS rx),
  STRUCT('autosar' AS id, 'AUTOSAR' AS label, 'autosar' AS needle, FALSE AS boundary, r'autosar' AS rx),
  STRUCT('matlab' AS id, 'MATLAB' AS label, 'simulink' AS needle, FALSE AS boundary, r'simulink' AS rx),
  STRUCT('matlab' AS id, 'MATLAB' AS label, 'matlab' AS needle, FALSE AS boundary, r'matlab' AS rx),
  STRUCT('git' AS id, 'Git' AS label, 'github' AS needle, FALSE AS boundary, r'github' AS rx),
  STRUCT('git' AS id, 'Git' AS label, 'gitlab' AS needle, FALSE AS boundary, r'gitlab' AS rx),
  STRUCT('git' AS id, 'Git' AS label, 'git' AS needle, TRUE AS boundary, r'git' AS rx),
  STRUCT('scrum' AS id, 'Scrum' AS label, 'product owner' AS needle, FALSE AS boundary, r'product owner' AS rx),
  STRUCT('scrum' AS id, 'Scrum' AS label, 'scrum master' AS needle, FALSE AS boundary, r'scrum master' AS rx),
  STRUCT('scrum' AS id, 'Scrum' AS label, 'scrum' AS needle, TRUE AS boundary, r'scrum' AS rx),
  STRUCT('agile' AS id, 'Agile' AS label, 'agile' AS needle, TRUE AS boundary, r'agile' AS rx),
  STRUCT('forklift' AS id, 'Forklift' AS label, 'vysokozdvizneho voziku' AS needle, FALSE AS boundary, r'vysokozdvizneho voziku' AS rx),
  STRUCT('forklift' AS id, 'Forklift' AS label, 'staplerfuhrerschein' AS needle, FALSE AS boundary, r'staplerfuhrerschein' AS rx),
  STRUCT('forklift' AS id, 'Forklift' AS label, 'vysokozdvizny vozik' AS needle, FALSE AS boundary, r'vysokozdvizny vozik' AS rx),
  STRUCT('forklift' AS id, 'Forklift' AS label, 'gabelstaplerfahrer' AS needle, FALSE AS boundary, r'gabelstaplerfahrer' AS rx),
  STRUCT('forklift' AS id, 'Forklift' AS label, 'flurfoerdermittel' AS needle, FALSE AS boundary, r'flurfoerdermittel' AS rx),
  STRUCT('forklift' AS id, 'Forklift' AS label, 'heftruckchauffeur' AS needle, FALSE AS boundary, r'heftruckchauffeur' AS rx),
  STRUCT('forklift' AS id, 'Forklift' AS label, 'staplerfahrer' AS needle, FALSE AS boundary, r'staplerfahrer' AS rx),
  STRUCT('forklift' AS id, 'Forklift' AS label, 'staplerschein' AS needle, FALSE AS boundary, r'staplerschein' AS rx),
  STRUCT('forklift' AS id, 'Forklift' AS label, 'gabelstapler' AS needle, FALSE AS boundary, r'gabelstapler' AS rx),
  STRUCT('forklift' AS id, 'Forklift' AS label, 'heftruck' AS needle, FALSE AS boundary, r'heftruck' AS rx),
  STRUCT('forklift' AS id, 'Forklift' AS label, 'forklift' AS needle, FALSE AS boundary, r'forklift' AS rx),
  STRUCT('cnc' AS id, 'CNC' AS label, 'zerspanung' AS needle, FALSE AS boundary, r'zerspanung' AS rx),
  STRUCT('cnc' AS id, 'CNC' AS label, 'fraeser' AS needle, FALSE AS boundary, r'fraeser' AS rx),
  STRUCT('cnc' AS id, 'CNC' AS label, 'fraser' AS needle, FALSE AS boundary, r'fraser' AS rx),
  STRUCT('cnc' AS id, 'CNC' AS label, 'dreher' AS needle, FALSE AS boundary, r'dreher' AS rx),
  STRUCT('cnc' AS id, 'CNC' AS label, 'cnc' AS needle, TRUE AS boundary, r'cnc' AS rx),
  STRUCT('welding' AS id, 'Welding' AS label, 'schweisser' AS needle, FALSE AS boundary, r'schweisser' AS rx),
  STRUCT('welding' AS id, 'Welding' AS label, 'schweissen' AS needle, FALSE AS boundary, r'schweissen' AS rx),
  STRUCT('welding' AS id, 'Welding' AS label, 'schweißer' AS needle, FALSE AS boundary, r'schweißer' AS rx),
  STRUCT('welding' AS id, 'Welding' AS label, 'schweißen' AS needle, FALSE AS boundary, r'schweißen' AS rx),
  STRUCT('welding' AS id, 'Welding' AS label, 'svarovac' AS needle, FALSE AS boundary, r'svarovac' AS rx),
  STRUCT('welding' AS id, 'Welding' AS label, 'welder' AS needle, FALSE AS boundary, r'welder' AS rx),
  STRUCT('welding' AS id, 'Welding' AS label, 'lasser' AS needle, FALSE AS boundary, r'lasser' AS rx),
  STRUCT('welding' AS id, 'Welding' AS label, 'svarec' AS needle, FALSE AS boundary, r'svarec' AS rx),
  STRUCT('sps' AS id, 'PLC / SPS' AS label, 'speicherprogrammierbar' AS needle, FALSE AS boundary, r'speicherprogrammierbar' AS rx),
  STRUCT('sps' AS id, 'PLC / SPS' AS label, 'plc programming' AS needle, FALSE AS boundary, r'plc programming' AS rx),
  STRUCT('sps' AS id, 'PLC / SPS' AS label, 'siemens tia' AS needle, FALSE AS boundary, r'siemens tia' AS rx),
  STRUCT('sps' AS id, 'PLC / SPS' AS label, 'sps' AS needle, TRUE AS boundary, r'sps' AS rx),
  STRUCT('electrician' AS id, 'Electrical' AS label, 'elektrofachkraft' AS needle, FALSE AS boundary, r'elektrofachkraft' AS rx),
  STRUCT('electrician' AS id, 'Electrical' AS label, 'elektromonteur' AS needle, FALSE AS boundary, r'elektromonteur' AS rx),
  STRUCT('electrician' AS id, 'Electrical' AS label, 'elektroniker' AS needle, FALSE AS boundary, r'elektroniker' AS rx),
  STRUCT('electrician' AS id, 'Electrical' AS label, 'electrician' AS needle, FALSE AS boundary, r'electrician' AS rx),
  STRUCT('electrician' AS id, 'Electrical' AS label, 'elektriker' AS needle, FALSE AS boundary, r'elektriker' AS rx),
  STRUCT('mechatronics' AS id, 'Mechatronics' AS label, 'mechatroniker' AS needle, FALSE AS boundary, r'mechatroniker' AS rx),
  STRUCT('mechatronics' AS id, 'Mechatronics' AS label, 'mechatronics' AS needle, FALSE AS boundary, r'mechatronics' AS rx),
  STRUCT('mechatronics' AS id, 'Mechatronics' AS label, 'mechatronik' AS needle, FALSE AS boundary, r'mechatronik' AS rx),
  STRUCT('crane' AS id, 'Crane' AS label, 'kranfuehrer' AS needle, FALSE AS boundary, r'kranfuehrer' AS rx),
  STRUCT('crane' AS id, 'Crane' AS label, 'kranfuhrer' AS needle, FALSE AS boundary, r'kranfuhrer' AS rx),
  STRUCT('crane' AS id, 'Crane' AS label, 'kranschein' AS needle, FALSE AS boundary, r'kranschein' AS rx),
  STRUCT('crane' AS id, 'Crane' AS label, 'hallenkran' AS needle, FALSE AS boundary, r'hallenkran' AS rx),
  STRUCT('crane' AS id, 'Crane' AS label, 'portalkran' AS needle, FALSE AS boundary, r'portalkran' AS rx),
  STRUCT('driving_b' AS id, 'Driving licence B' AS label, 'fuhrerschein klasse b' AS needle, FALSE AS boundary, r'fuhrerschein klasse b' AS rx),
  STRUCT('driving_b' AS id, 'Driving licence B' AS label, 'driving licence b' AS needle, FALSE AS boundary, r'driving licence b' AS rx),
  STRUCT('driving_b' AS id, 'Driving licence B' AS label, 'driver license b' AS needle, FALSE AS boundary, r'driver license b' AS rx),
  STRUCT('driving_b' AS id, 'Driving licence B' AS label, 'fuhrerschein b' AS needle, FALSE AS boundary, r'fuhrerschein b' AS rx),
  STRUCT('driving_b' AS id, 'Driving licence B' AS label, 'rijbewijs b' AS needle, FALSE AS boundary, r'rijbewijs b' AS rx),
  STRUCT('driving_ce' AS id, 'Driving licence C/CE' AS label, 'fuhrerschein klasse c' AS needle, FALSE AS boundary, r'fuhrerschein klasse c' AS rx),
  STRUCT('driving_ce' AS id, 'Driving licence C/CE' AS label, 'fuhrerschein ce' AS needle, FALSE AS boundary, r'fuhrerschein ce' AS rx),
  STRUCT('driving_ce' AS id, 'Driving licence C/CE' AS label, 'rijbewijs ce' AS needle, FALSE AS boundary, r'rijbewijs ce' AS rx),
  STRUCT('driving_ce' AS id, 'Driving licence C/CE' AS label, 'c+e' AS needle, TRUE AS boundary, r'c\+e' AS rx),
  STRUCT('german' AS id, 'German' AS label, 'deutschkenntnisse' AS needle, FALSE AS boundary, r'deutschkenntnisse' AS rx),
  STRUCT('german' AS id, 'German' AS label, 'deutsche sprache' AS needle, FALSE AS boundary, r'deutsche sprache' AS rx),
  STRUCT('german' AS id, 'German' AS label, 'german language' AS needle, FALSE AS boundary, r'german language' AS rx),
  STRUCT('german' AS id, 'German' AS label, 'nemcina' AS needle, FALSE AS boundary, r'nemcina' AS rx),
  STRUCT('german' AS id, 'German' AS label, 'deutsch' AS needle, TRUE AS boundary, r'deutsch' AS rx),
  STRUCT('german' AS id, 'German' AS label, 'duits' AS needle, FALSE AS boundary, r'duits' AS rx),
  STRUCT('english' AS id, 'English' AS label, 'englischkenntnisse' AS needle, FALSE AS boundary, r'englischkenntnisse' AS rx),
  STRUCT('english' AS id, 'English' AS label, 'english language' AS needle, FALSE AS boundary, r'english language' AS rx),
  STRUCT('english' AS id, 'English' AS label, 'anglictina' AS needle, FALSE AS boundary, r'anglictina' AS rx),
  STRUCT('english' AS id, 'English' AS label, 'engels' AS needle, FALSE AS boundary, r'engels' AS rx),
  STRUCT('dutch' AS id, 'Dutch' AS label, 'niederlandisch' AS needle, FALSE AS boundary, r'niederlandisch' AS rx),
  STRUCT('dutch' AS id, 'Dutch' AS label, 'dutch language' AS needle, FALSE AS boundary, r'dutch language' AS rx),
  STRUCT('dutch' AS id, 'Dutch' AS label, 'nederlands' AS needle, TRUE AS boundary, r'nederlands' AS rx),
  STRUCT('czech' AS id, 'Czech' AS label, 'czech language' AS needle, FALSE AS boundary, r'czech language' AS rx),
  STRUCT('czech' AS id, 'Czech' AS label, 'tschechisch' AS needle, FALSE AS boundary, r'tschechisch' AS rx),
  STRUCT('czech' AS id, 'Czech' AS label, 'cestina' AS needle, FALSE AS boundary, r'cestina' AS rx),
  STRUCT('french' AS id, 'French' AS label, 'french language' AS needle, FALSE AS boundary, r'french language' AS rx),
  STRUCT('french' AS id, 'French' AS label, 'franzosisch' AS needle, FALSE AS boundary, r'franzosisch' AS rx),
  STRUCT('french' AS id, 'French' AS label, 'francais' AS needle, FALSE AS boundary, r'francais' AS rx),
  STRUCT('nursing' AS id, 'Nursing' AS label, 'gesundheits- und krankenpfleger' AS needle, FALSE AS boundary, r'gesundheits- und krankenpfleger' AS rx),
  STRUCT('nursing' AS id, 'Nursing' AS label, 'examinierte pflege' AS needle, FALSE AS boundary, r'examinierte pflege' AS rx),
  STRUCT('nursing' AS id, 'Nursing' AS label, 'registered nurse' AS needle, FALSE AS boundary, r'registered nurse' AS rx),
  STRUCT('nursing' AS id, 'Nursing' AS label, 'pflegefachkraft' AS needle, FALSE AS boundary, r'pflegefachkraft' AS rx),
  STRUCT('nursing' AS id, 'Nursing' AS label, 'verpleegkundige' AS needle, FALSE AS boundary, r'verpleegkundige' AS rx),
  STRUCT('datev' AS id, 'DATEV' AS label, 'datev' AS needle, FALSE AS boundary, r'datev' AS rx)
]);

CREATE OR REPLACE TABLE `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offer_skills`
CLUSTER BY job_key, skill_id AS
WITH jobs AS (
  SELECT
    j.job_key,
    hay(j.title, j.description_excerpt, d.description) AS hay
  FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country` j
  LEFT JOIN `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_descriptions` d
    USING (job_key)
)
SELECT
  job_key,
  skill_id,
  skill_label,
  evidence,
  source
FROM (
  SELECT
    job_key,
    skill_id,
    skill_label,
    evidence,
    source,
    ROW_NUMBER() OVER (PARTITION BY job_key, skill_id ORDER BY source, evidence) AS rn
  FROM (
    SELECT
      j.job_key,
      n.id AS skill_id,
      n.label AS skill_label,
      n.needle AS evidence,
      'description' AS source
    FROM jobs j
    JOIN `poetic-sentinel-402405.apply_jobs_jobs2_prod.skill_needles` n
      ON IF(
        n.boundary,
        REGEXP_CONTAINS(j.hay, CONCAT(r'(^|[^a-z0-9+.#])', n.rx, r'([^a-z0-9+.#]|$)')),
        STRPOS(j.hay, n.needle) > 0
      )

    UNION ALL

    SELECT
      jo.job_key,
      n.id AS skill_id,
      n.label AS skill_label,
      fold(h.skill) AS evidence,
      'harvest' AS source
    FROM `poetic-sentinel-402405.apply_jobs.job_skills` h
    JOIN `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country` jo
      ON jo.url_norm = `poetic-sentinel-402405.apply_jobs_jobs2_prod.url_norm`(h.url)
    JOIN `poetic-sentinel-402405.apply_jobs_jobs2_prod.skill_needles` n
      ON fold(h.skill) = n.needle OR fold(h.skill) = n.id
  )
)
WHERE rn = 1
QUALIFY ROW_NUMBER() OVER (PARTITION BY job_key ORDER BY source, skill_id) <= 16;

CREATE OR REPLACE TABLE `poetic-sentinel-402405.apply_jobs_jobs2_dev.skill_needles`
AS SELECT * FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.skill_needles`;

CREATE OR REPLACE TABLE `poetic-sentinel-402405.apply_jobs_jobs2_dev.job_offer_skills`
CLUSTER BY job_key, skill_id AS
SELECT * FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offer_skills`;
