-- Generated by scripts/bq/gen_patches.ts — headquarters + recovered job location.

CREATE TEMP FUNCTION fold(s STRING) AS (
  REGEXP_REPLACE(NORMALIZE(LOWER(IFNULL(s, "")), NFD), r'\p{M}', '')
);

CREATE TEMP FUNCTION is_generic_loc(s STRING) AS (
  fold(s) IN (
    '', 'default', 'unknown', 'n/a', 'na', 'none', 'null', '-', '.',
    'eu (other)', 'europe', 'worldwide', 'global',
    'germany', 'de', 'deutschland', 'czechia', 'cz', 'czech republic',
    'netherlands', 'nl', 'holland', 'france', 'fr', 'united kingdom', 'gb', 'uk',
    'united states', 'us', 'usa', 'austria', 'at', 'switzerland', 'ch',
    'belgium', 'be', 'poland', 'pl', 'spain', 'es', 'italy', 'it', 'sweden', 'se',
    'singapore', 'sg', 'ireland', 'ie', 'denmark', 'dk', 'norway', 'no', 'finland', 'fi',
    'luxembourg', 'lu', 'croatia', 'hr', 'slovakia', 'sk', 'romania', 'ro', 'slovenia', 'si',
    'malta', 'mt', 'latvia', 'lv', 'estonia', 'ee', 'lithuania', 'lt', 'hungary', 'hu',
    'portugal', 'pt', 'greece', 'gr', 'japan', 'jp', 'canada', 'ca', 'australia', 'au',
    'india', 'in', 'china', 'cn', 'brazil', 'br', 'mexico', 'mx'
  )
  OR REGEXP_CONTAINS(fold(s), r'^[a-z]{2}$')
  OR REGEXP_CONTAINS(fold(s), r'^nl[0-9a-z]{2,3}(,| |$)')
  OR STARTS_WITH(fold(s), 'obec/')
);

CREATE OR REPLACE TABLE `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp`
CLUSTER BY country_iso2, public_rank AS
WITH cities AS (
  SELECT city, fold(city) AS f
  FROM UNNEST([
  'Berlin',
  'Hamburg',
  'Munich',
  'München',
  'Cologne',
  'Köln',
  'Frankfurt',
  'Stuttgart',
  'Düsseldorf',
  'Dortmund',
  'Leipzig',
  'Bremen',
  'Dresden',
  'Hannover',
  'Nuremberg',
  'Nürnberg',
  'Duisburg',
  'Bochum',
  'Wuppertal',
  'Bielefeld',
  'Bonn',
  'Münster',
  'Karlsruhe',
  'Mannheim',
  'Augsburg',
  'Wiesbaden',
  'Gelsenkirchen',
  'Aachen',
  'Braunschweig',
  'Kiel',
  'Chemnitz',
  'Magdeburg',
  'Freiburg',
  'Krefeld',
  'Mainz',
  'Lübeck',
  'Erfurt',
  'Rostock',
  'Kassel',
  'Hagen',
  'Potsdam',
  'Saarbrücken',
  'Hamm',
  'Ludwigshafen',
  'Oldenburg',
  'Osnabrück',
  'Leverkusen',
  'Heidelberg',
  'Darmstadt',
  'Solingen',
  'Regensburg',
  'Paderborn',
  'Ingolstadt',
  'Würzburg',
  'Wolfsburg',
  'Ulm',
  'Heilbronn',
  'Göttingen',
  'Offenbach',
  'Reutlingen',
  'Koblenz',
  'Jena',
  'Erlangen',
  'Trier',
  'Siegen',
  'Hildesheim',
  'Cottbus',
  'Amsterdam',
  'Rotterdam',
  'The Hague',
  'Den Haag',
  'Utrecht',
  'Eindhoven',
  'Groningen',
  'Tilburg',
  'Almere',
  'Breda',
  'Nijmegen',
  'Arnhem',
  'Haarlem',
  'Enschede',
  'Amersfoort',
  'Zaanstad',
  'Apeldoorn',
  'Maastricht',
  'Leiden',
  'Dordrecht',
  'Zoetermeer',
  'Zwolle',
  'Prague',
  'Praha',
  'Brno',
  'Ostrava',
  'Plzen',
  'Plzeň',
  'Liberec',
  'Olomouc',
  'Ceske Budejovice',
  'Hradec Kralove',
  'Pardubice',
  'Zlin',
  'Havirov',
  'Kladno',
  'Opava',
  'Karlovy Vary',
  'Jihlava',
  'Teplice',
  'Paris',
  'Lyon',
  'Marseille',
  'Toulouse',
  'Nantes',
  'Strasbourg',
  'Montpellier',
  'Bordeaux',
  'Lille',
  'Rennes',
  'Reims',
  'Grenoble',
  'Vienna',
  'Wien',
  'Graz',
  'Linz',
  'Salzburg',
  'Innsbruck',
  'Zurich',
  'Zürich',
  'Geneva',
  'Basel',
  'Bern',
  'Lausanne',
  'Winterthur',
  'Brussels',
  'Brussel',
  'Antwerp',
  'Antwerpen',
  'Ghent',
  'Gent',
  'Liège',
  'Charleroi',
  'London',
  'Manchester',
  'Birmingham',
  'Leeds',
  'Glasgow',
  'Liverpool',
  'Bristol',
  'Edinburgh',
  'Cambridge',
  'Oxford',
  'Newcastle',
  'New York',
  'San Francisco',
  'Cupertino',
  'Seattle',
  'Austin',
  'Boston',
  'Chicago',
  'Los Angeles',
  'Washington',
  'Atlanta',
  'Denver',
  'Dallas',
  'Singapore',
  'Dublin',
  'Stockholm',
  'Copenhagen',
  'Oslo',
  'Helsinki',
  'Warsaw',
  'Krakow',
  'Madrid',
  'Barcelona',
  'Milan',
  'Rome',
  'Lisbon',
  'Luxembourg',
  'Walldorf',
  'Montabaur'
  ]) AS city
),
nuts AS (
  SELECT * FROM UNNEST([
  STRUCT('nl11' AS prefix, 'Groningen' AS label),
  STRUCT('nl12' AS prefix, 'Friesland' AS label),
  STRUCT('nl13' AS prefix, 'Drenthe' AS label),
  STRUCT('nl21' AS prefix, 'Overijssel' AS label),
  STRUCT('nl22' AS prefix, 'Gelderland' AS label),
  STRUCT('nl23' AS prefix, 'Flevoland' AS label),
  STRUCT('nl31' AS prefix, 'Utrecht' AS label),
  STRUCT('nl32' AS prefix, 'Noord-Holland' AS label),
  STRUCT('nl33' AS prefix, 'Zuid-Holland' AS label),
  STRUCT('nl34' AS prefix, 'Zeeland' AS label),
  STRUCT('nl41' AS prefix, 'Noord-Brabant' AS label),
  STRUCT('nl42' AS prefix, 'Limburg' AS label)
  ])
),
titled AS (
  SELECT
    j.job_key,
    ARRAY_AGG(c.city ORDER BY LENGTH(c.f) DESC LIMIT 1)[SAFE_OFFSET(0)] AS title_city
  FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country` j
  JOIN cities c
    ON STRPOS(CONCAT(' ', fold(CONCAT(IFNULL(j.title, ''), ' ', IFNULL(j.company, ''))), ' '), CONCAT(' ', c.f, ' ')) > 0
  GROUP BY j.job_key
),
posted AS (
  SELECT
    j.job_key,
    ARRAY_AGG(c.city ORDER BY LENGTH(c.f) DESC LIMIT 1)[SAFE_OFFSET(0)] AS loc_city
  FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country` j
  JOIN cities c
    ON STRPOS(CONCAT(' ', fold(IFNULL(j.job_location, '')), ' '), CONCAT(' ', c.f, ' ')) > 0
  GROUP BY j.job_key
),
company_hq AS (
  SELECT company, city FROM (
    SELECT
      j.company,
      COALESCE(t.title_city, p.loc_city) AS city,
      COUNT(*) AS n
    FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country` j
    LEFT JOIN titled t USING (job_key)
    LEFT JOIN posted p USING (job_key)
    WHERE COALESCE(t.title_city, p.loc_city) IS NOT NULL
      AND IFNULL(j.company, '') != ''
    GROUP BY 1, 2
  )
  QUALIFY ROW_NUMBER() OVER (PARTITION BY company ORDER BY n DESC) = 1
)
SELECT
  j.* EXCEPT (job_location, headquarters_location),
  CASE
    WHEN REGEXP_CONTAINS(LOWER(CONCAT(IFNULL(j.is_remote, ''), ' ', IFNULL(j.title, ''))), r'remote|homeoffice|home office|hybrid')
         AND t.title_city IS NULL
         AND is_generic_loc(j.job_location)
      THEN j.job_location
    WHEN t.title_city IS NOT NULL THEN t.title_city
    WHEN REGEXP_CONTAINS(fold(IFNULL(j.job_location, '')), r'\bnl[0-9]{2}') THEN
      (SELECT label FROM nuts n
       WHERE STARTS_WITH(REGEXP_EXTRACT(fold(j.job_location), r'nl[0-9]{2}'), n.prefix)
       LIMIT 1)
    WHEN p.loc_city IS NOT NULL THEN p.loc_city
    WHEN is_generic_loc(j.job_location) THEN COALESCE(ch.city, h.country_name, j.job_location)
    ELSE j.job_location
  END AS job_location,
  COALESCE(
    ch.city,
    t.title_city,
    p.loc_city,
    IF(is_generic_loc(j.headquarters_location), NULL, j.headquarters_location),
    h.country_name,
    j.headquarters_location
  ) AS headquarters_location
FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country` j
LEFT JOIN titled t USING (job_key)
LEFT JOIN posted p USING (job_key)
LEFT JOIN company_hq ch ON ch.company = j.company
LEFT JOIN (
  SELECT iso2, name AS country_name FROM UNNEST([
    STRUCT('DE' AS iso2, 'Germany' AS name), STRUCT('NL','Netherlands'), STRUCT('CZ','Czechia'),
    STRUCT('GB','United Kingdom'), STRUCT('US','United States'), STRUCT('FR','France'),
    STRUCT('AT','Austria'), STRUCT('CH','Switzerland'), STRUCT('BE','Belgium'),
    STRUCT('PL','Poland'), STRUCT('SE','Sweden'), STRUCT('SG','Singapore'),
    STRUCT('ES','Spain'), STRUCT('IT','Italy'), STRUCT('IE','Ireland'),
    STRUCT('DK','Denmark'), STRUCT('NO','Norway'), STRUCT('FI','Finland'),
    STRUCT('LU','Luxembourg'), STRUCT('SK','Slovakia'), STRUCT('RO','Romania'),
    STRUCT('HR','Croatia'), STRUCT('MT','Malta'), STRUCT('SI','Slovenia'),
    STRUCT('LV','Latvia'), STRUCT('EE','Estonia'), STRUCT('CA','Canada'),
    STRUCT('PT','Portugal'), STRUCT('LT','Lithuania'), STRUCT('CY','Cyprus'),
    STRUCT('BG','Bulgaria'), STRUCT('HU','Hungary'), STRUCT('JP','Japan'),
    STRUCT('GR','Greece'), STRUCT('AU','Australia'), STRUCT('AE','UAE'),
    STRUCT('IS','Iceland'), STRUCT('BR','Brazil'), STRUCT('CN','China'),
    STRUCT('MX','Mexico'), STRUCT('IN','India'), STRUCT('KR','South Korea'),
    STRUCT('IL','Israel'), STRUCT('ZZ','Unknown')
  ])
) h ON h.iso2 = j.country_iso2;

CREATE OR REPLACE TABLE `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country`
CLUSTER BY country_iso2, public_rank AS
SELECT * FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp`;

DROP TABLE `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp`;
