-- Re-tag serving specialties to specific occupational fields (multi-label).
-- Unmatched jobs become Weitere. Does not rebuild job_key / public_rank.

CREATE OR REPLACE TABLE `poetic-sentinel-402405.apply_jobs_jobs2_prod.specialty_needles` AS
SELECT * FROM UNNEST([
  STRUCT('produktion' AS id, 'produktionsmitarbeiter' AS needle),
  STRUCT('produktion' AS id, 'produktionshelfer' AS needle),
  STRUCT('produktion' AS id, 'produktionsfachkraft' AS needle),
  STRUCT('produktion' AS id, 'produktionstechn' AS needle),
  STRUCT('produktion' AS id, 'produktions' AS needle),
  STRUCT('produktion' AS id, 'productiemedewerker' AS needle),
  STRUCT('produktion' AS id, 'procesoperator' AS needle),
  STRUCT('produktion' AS id, 'operator' AS needle),
  STRUCT('produktion' AS id, 'assembler' AS needle),
  STRUCT('produktion' AS id, 'manufacturing' AS needle),
  STRUCT('produktion' AS id, 'production worker' AS needle),
  STRUCT('produktion' AS id, 'production operator' AS needle),
  STRUCT('produktion' AS id, 'metallhelfer' AS needle),
  STRUCT('fertigung' AS id, 'fertigung' AS needle),
  STRUCT('fertigung' AS id, 'fertigungs' AS needle),
  STRUCT('fertigung' AS id, 'fertigungstechnik' AS needle),
  STRUCT('fertigung' AS id, 'industriemechaniker' AS needle),
  STRUCT('fertigung' AS id, 'maschinen- und anlagenführer' AS needle),
  STRUCT('fertigung' AS id, 'maschinen- und anlagenfuehrer' AS needle),
  STRUCT('fertigung' AS id, 'maschinenbediener' AS needle),
  STRUCT('fertigung' AS id, 'maschinenführer' AS needle),
  STRUCT('fertigung' AS id, 'maschinenfuehrer' AS needle),
  STRUCT('fertigung' AS id, 'anlagenführer' AS needle),
  STRUCT('fertigung' AS id, 'anlagenfuehrer' AS needle),
  STRUCT('fertigung' AS id, 'anlagenbediener' AS needle),
  STRUCT('fertigung' AS id, 'zerspanungsmechaniker' AS needle),
  STRUCT('fertigung' AS id, 'zerspanung' AS needle),
  STRUCT('fertigung' AS id, 'schweißer' AS needle),
  STRUCT('fertigung' AS id, 'schweisser' AS needle),
  STRUCT('fertigung' AS id, 'welder' AS needle),
  STRUCT('fertigung' AS id, 'svářeč' AS needle),
  STRUCT('fertigung' AS id, 'svarovac' AS needle),
  STRUCT('fertigung' AS id, 'schlosser' AS needle),
  STRUCT('fertigung' AS id, 'cnc' AS needle),
  STRUCT('fertigung' AS id, 'dreher' AS needle),
  STRUCT('fertigung' AS id, 'fräser' AS needle),
  STRUCT('fertigung' AS id, 'fraeser' AS needle),
  STRUCT('fertigung' AS id, 'montierer' AS needle),
  STRUCT('fertigung' AS id, 'montagehelfer' AS needle),
  STRUCT('fertigung' AS id, 'mechatroniker' AS needle),
  STRUCT('fertigung' AS id, 'instandhaltung' AS needle),
  STRUCT('fertigung' AS id, 'instandhalter' AS needle),
  STRUCT('fertigung' AS id, 'werkzeugmacher' AS needle),
  STRUCT('fertigung' AS id, 'verfahrenstechnik' AS needle),
  STRUCT('fertigung' AS id, 'werkvoorbereider' AS needle),
  STRUCT('ingenieurwesen' AS id, 'ingenieur' AS needle),
  STRUCT('ingenieurwesen' AS id, 'engineer' AS needle),
  STRUCT('ingenieurwesen' AS id, 'engineering' AS needle),
  STRUCT('ingenieurwesen' AS id, 'konstrukteur' AS needle),
  STRUCT('ingenieurwesen' AS id, 'konstruktion' AS needle),
  STRUCT('ingenieurwesen' AS id, 'entwicklungsingenieur' AS needle),
  STRUCT('ingenieurwesen' AS id, 'maschinenbau' AS needle),
  STRUCT('ingenieurwesen' AS id, 'bauingenieur' AS needle),
  STRUCT('ingenieurwesen' AS id, 'verfahrenstechniker' AS needle),
  STRUCT('forschung' AS id, 'forschung' AS needle),
  STRUCT('forschung' AS id, 'forscher' AS needle),
  STRUCT('forschung' AS id, 'scientist' AS needle),
  STRUCT('forschung' AS id, 'wissenschaftlicher mitarbeiter' AS needle),
  STRUCT('forschung' AS id, 'research scientist' AS needle),
  STRUCT('forschung' AS id, 'r&d' AS needle),
  STRUCT('forschung' AS id, 'f&e' AS needle),
  STRUCT('forschung' AS id, 'postdoc' AS needle),
  STRUCT('forschung' AS id, 'laborant' AS needle),
  STRUCT('forschung' AS id, 'laboratory' AS needle),
  STRUCT('personal' AS id, 'personalreferent' AS needle),
  STRUCT('personal' AS id, 'personalsachbearbeiter' AS needle),
  STRUCT('personal' AS id, 'personalentwicklung' AS needle),
  STRUCT('personal' AS id, 'personalleiter' AS needle),
  STRUCT('personal' AS id, 'personalfach' AS needle),
  STRUCT('personal' AS id, 'personalwesen' AS needle),
  STRUCT('personal' AS id, 'human resources' AS needle),
  STRUCT('personal' AS id, 'hr manager' AS needle),
  STRUCT('personal' AS id, 'hr business' AS needle),
  STRUCT('personal' AS id, 'recruiter' AS needle),
  STRUCT('personal' AS id, 'recruiting' AS needle),
  STRUCT('personal' AS id, 'talent acquisition' AS needle),
  STRUCT('personal' AS id, 'payroll' AS needle),
  STRUCT('personal' AS id, 'entgeltabrechnung' AS needle),
  STRUCT('personal' AS id, 'ausbilder' AS needle),
  STRUCT('it' AS id, 'softwareentwickler' AS needle),
  STRUCT('it' AS id, 'software engineer' AS needle),
  STRUCT('it' AS id, 'software developer' AS needle),
  STRUCT('it' AS id, 'fachinformatiker' AS needle),
  STRUCT('it' AS id, 'informatiker' AS needle),
  STRUCT('it' AS id, 'entwickler' AS needle),
  STRUCT('it' AS id, 'developer' AS needle),
  STRUCT('it' AS id, 'programmer' AS needle),
  STRUCT('it' AS id, 'devops' AS needle),
  STRUCT('it' AS id, 'sysadmin' AS needle),
  STRUCT('it' AS id, 'systemadministrator' AS needle),
  STRUCT('it' AS id, 'it-administrator' AS needle),
  STRUCT('it' AS id, 'it administrator' AS needle),
  STRUCT('it' AS id, 'it-support' AS needle),
  STRUCT('it' AS id, 'it support' AS needle),
  STRUCT('it' AS id, 'it consultant' AS needle),
  STRUCT('it' AS id, 'it-berater' AS needle),
  STRUCT('it' AS id, 'fullstack' AS needle),
  STRUCT('it' AS id, 'full-stack' AS needle),
  STRUCT('it' AS id, 'backend' AS needle),
  STRUCT('it' AS id, 'frontend' AS needle),
  STRUCT('it' AS id, 'javascript' AS needle),
  STRUCT('it' AS id, 'typescript' AS needle),
  STRUCT('it' AS id, 'python' AS needle),
  STRUCT('it' AS id, 'java ' AS needle),
  STRUCT('it' AS id, 'kubernetes' AS needle),
  STRUCT('it' AS id, 'cloud engineer' AS needle),
  STRUCT('it' AS id, 'application manager' AS needle),
  STRUCT('it' AS id, 'sap berat' AS needle),
  STRUCT('it' AS id, 'sap consultant' AS needle),
  STRUCT('it' AS id, 'data engineer' AS needle),
  STRUCT('it' AS id, 'platform engineer' AS needle),
  STRUCT('it' AS id, 'sre' AS needle),
  STRUCT('it' AS id, 'cybersecurity' AS needle),
  STRUCT('it' AS id, 'infosec' AS needle),
  STRUCT('it' AS id, 'appsec' AS needle),
  STRUCT('it' AS id, 'webentwickler' AS needle),
  STRUCT('logistik' AS id, 'logistik' AS needle),
  STRUCT('logistik' AS id, 'lagerist' AS needle),
  STRUCT('logistik' AS id, 'lagermitarbeiter' AS needle),
  STRUCT('logistik' AS id, 'lagerhelfer' AS needle),
  STRUCT('logistik' AS id, 'lagerarbeiter' AS needle),
  STRUCT('logistik' AS id, 'lagerlogistik' AS needle),
  STRUCT('logistik' AS id, 'fachkraft für lager' AS needle),
  STRUCT('logistik' AS id, 'fachkraft fuer lager' AS needle),
  STRUCT('logistik' AS id, 'kommissionierer' AS needle),
  STRUCT('logistik' AS id, 'kommissionier' AS needle),
  STRUCT('logistik' AS id, 'staplerfahrer' AS needle),
  STRUCT('logistik' AS id, 'gabelstapler' AS needle),
  STRUCT('logistik' AS id, 'warehouse' AS needle),
  STRUCT('logistik' AS id, 'supply chain' AS needle),
  STRUCT('logistik' AS id, 'spedition' AS needle),
  STRUCT('logistik' AS id, 'disponent' AS needle),
  STRUCT('logistik' AS id, 'lkw-fahrer' AS needle),
  STRUCT('logistik' AS id, 'lkw fahrer' AS needle),
  STRUCT('logistik' AS id, 'kraftfahrer' AS needle),
  STRUCT('logistik' AS id, 'berufskraftfahrer' AS needle),
  STRUCT('logistik' AS id, 'lieferfahrer' AS needle),
  STRUCT('logistik' AS id, 'kurier' AS needle),
  STRUCT('logistik' AS id, 'lager' AS needle),
  STRUCT('logistik' AS id, 'logistiek' AS needle),
  STRUCT('logistik' AS id, 'magazijn' AS needle),
  STRUCT('logistik' AS id, 'heftruck' AS needle),
  STRUCT('logistik' AS id, 'vrachtwagen' AS needle),
  STRUCT('logistik' AS id, 'chauffeur' AS needle),
  STRUCT('logistik' AS id, 'postbote' AS needle),
  STRUCT('logistik' AS id, 'paketzustell' AS needle),
  STRUCT('logistik' AS id, 'skladník' AS needle),
  STRUCT('logistik' AS id, 'skladnici' AS needle),
  STRUCT('logistik' AS id, 'skladni' AS needle),
  STRUCT('logistik' AS id, 'transportarbeiter' AS needle),
  STRUCT('logistik' AS id, 'versandmitarbeiter' AS needle),
  STRUCT('logistik' AS id, 'versand' AS needle),
  STRUCT('logistik' AS id, 'řidič' AS needle),
  STRUCT('logistik' AS id, 'ridic' AS needle),
  STRUCT('logistik' AS id, 'taxikář' AS needle),
  STRUCT('logistik' AS id, 'taxikar' AS needle),
  STRUCT('logistik' AS id, 'taxi ' AS needle),
  STRUCT('logistik' AS id, ' taxik' AS needle),
  STRUCT('logistik' AS id, 'briefträger' AS needle),
  STRUCT('logistik' AS id, 'brieftraeger' AS needle),
  STRUCT('logistik' AS id, 'postzustell' AS needle),
  STRUCT('qualitaet' AS id, 'qualitätsmanagement' AS needle),
  STRUCT('qualitaet' AS id, 'qualitaetsmanagement' AS needle),
  STRUCT('qualitaet' AS id, 'qualitätssicherung' AS needle),
  STRUCT('qualitaet' AS id, 'qualitaetssicherung' AS needle),
  STRUCT('qualitaet' AS id, 'qualitätsprüfer' AS needle),
  STRUCT('qualitaet' AS id, 'qualitaetspruefer' AS needle),
  STRUCT('qualitaet' AS id, 'quality manager' AS needle),
  STRUCT('qualitaet' AS id, 'quality engineer' AS needle),
  STRUCT('qualitaet' AS id, 'quality assurance' AS needle),
  STRUCT('qualitaet' AS id, 'qmb' AS needle),
  STRUCT('qualitaet' AS id, 'iso 9001' AS needle),
  STRUCT('qualitaet' AS id, 'qs-mitarbeiter' AS needle),
  STRUCT('qualitaet' AS id, 'prüftechniker' AS needle),
  STRUCT('qualitaet' AS id, 'prueftechniker' AS needle),
  STRUCT('vertrieb' AS id, 'verkäufer' AS needle),
  STRUCT('vertrieb' AS id, 'verkaeufer' AS needle),
  STRUCT('vertrieb' AS id, 'verkaufer' AS needle),
  STRUCT('vertrieb' AS id, 'verkauf' AS needle),
  STRUCT('vertrieb' AS id, 'vertrieb' AS needle),
  STRUCT('vertrieb' AS id, 'kassierer' AS needle),
  STRUCT('vertrieb' AS id, 'kassiertätigkeit' AS needle),
  STRUCT('vertrieb' AS id, 'kassiertaetigkeit' AS needle),
  STRUCT('vertrieb' AS id, 'einzelhandel' AS needle),
  STRUCT('vertrieb' AS id, 'filialleiter' AS needle),
  STRUCT('vertrieb' AS id, 'marktleiter' AS needle),
  STRUCT('vertrieb' AS id, 'handelsfachwirt' AS needle),
  STRUCT('vertrieb' AS id, 'account manager' AS needle),
  STRUCT('vertrieb' AS id, 'key account' AS needle),
  STRUCT('vertrieb' AS id, 'sales ' AS needle),
  STRUCT('vertrieb' AS id, 'inside sales' AS needle),
  STRUCT('vertrieb' AS id, 'business development' AS needle),
  STRUCT('vertrieb' AS id, 'account executive' AS needle),
  STRUCT('vertrieb' AS id, 'verkoop' AS needle),
  STRUCT('vertrieb' AS id, 'verkoper' AS needle),
  STRUCT('vertrieb' AS id, 'warenverräumung' AS needle),
  STRUCT('vertrieb' AS id, 'warenverraeumung' AS needle),
  STRUCT('vertrieb' AS id, 'verräumung' AS needle),
  STRUCT('vertrieb' AS id, 'warenverräumer' AS needle),
  STRUCT('vertrieb' AS id, 'verräumer' AS needle),
  STRUCT('vertrieb' AS id, 'prodavač' AS needle),
  STRUCT('vertrieb' AS id, 'prodavac' AS needle),
  STRUCT('marketing' AS id, 'marketing' AS needle),
  STRUCT('marketing' AS id, 'merchandis' AS needle),
  STRUCT('marketing' AS id, 'warenpräsentation' AS needle),
  STRUCT('marketing' AS id, 'warenpraesentation' AS needle),
  STRUCT('marketing' AS id, 'brand manager' AS needle),
  STRUCT('marketing' AS id, 'kampagnen' AS needle),
  STRUCT('produkt' AS id, 'product manager' AS needle),
  STRUCT('produkt' AS id, 'produktmanager' AS needle),
  STRUCT('produkt' AS id, 'produktmanagement' AS needle),
  STRUCT('produkt' AS id, 'product owner' AS needle),
  STRUCT('produkt' AS id, 'produktowner' AS needle),
  STRUCT('projekt' AS id, 'projektleiter' AS needle),
  STRUCT('projekt' AS id, 'projektmanager' AS needle),
  STRUCT('projekt' AS id, 'projektkoordinator' AS needle),
  STRUCT('projekt' AS id, 'project manager' AS needle),
  STRUCT('projekt' AS id, 'project lead' AS needle),
  STRUCT('projekt' AS id, 'scrum master' AS needle),
  STRUCT('projekt' AS id, 'pmo' AS needle),
  STRUCT('projekt' AS id, 'agile coach' AS needle),
  STRUCT('projekt' AS id, 'projektmanagement' AS needle),
  STRUCT('projekt' AS id, 'program manager' AS needle),
  STRUCT('projekt' AS id, 'projectleider' AS needle),
  STRUCT('finanzen' AS id, 'financial analyst' AS needle),
  STRUCT('finanzen' AS id, 'investment analyst' AS needle),
  STRUCT('finanzen' AS id, 'treasury' AS needle),
  STRUCT('finanzen' AS id, 'finanzanalyst' AS needle),
  STRUCT('finanzen' AS id, 'finanzen' AS needle),
  STRUCT('finanzen' AS id, 'finanzwesen' AS needle),
  STRUCT('finanzen' AS id, 'cfa' AS needle),
  STRUCT('finanzen' AS id, 'mifid' AS needle),
  STRUCT('rechnungswesen' AS id, 'buchhalter' AS needle),
  STRUCT('rechnungswesen' AS id, 'buchhaltung' AS needle),
  STRUCT('rechnungswesen' AS id, 'finanzbuchhalter' AS needle),
  STRUCT('rechnungswesen' AS id, 'bilanzbuchhalter' AS needle),
  STRUCT('rechnungswesen' AS id, 'lohnbuchhalter' AS needle),
  STRUCT('rechnungswesen' AS id, 'rechnungswesen' AS needle),
  STRUCT('rechnungswesen' AS id, 'accountant' AS needle),
  STRUCT('rechnungswesen' AS id, 'steuerfach' AS needle),
  STRUCT('rechnungswesen' AS id, 'wirtschaftsprüf' AS needle),
  STRUCT('rechnungswesen' AS id, 'wirtschaftspruef' AS needle),
  STRUCT('controlling' AS id, 'controlling' AS needle),
  STRUCT('controlling' AS id, 'controller' AS needle),
  STRUCT('controlling' AS id, 'kostenrechnung' AS needle),
  STRUCT('verwaltung' AS id, 'verwaltung' AS needle),
  STRUCT('verwaltung' AS id, 'sachbearbeiter' AS needle),
  STRUCT('verwaltung' AS id, 'office manager' AS needle),
  STRUCT('verwaltung' AS id, 'bürokauf' AS needle),
  STRUCT('verwaltung' AS id, 'buerokauf' AS needle),
  STRUCT('verwaltung' AS id, 'verwaltungsfach' AS needle),
  STRUCT('verwaltung' AS id, 'verwaltungsangestellt' AS needle),
  STRUCT('verwaltung' AS id, 'sekretär' AS needle),
  STRUCT('verwaltung' AS id, 'sekretaer' AS needle),
  STRUCT('verwaltung' AS id, 'assistant' AS needle),
  STRUCT('verwaltung' AS id, 'assistent' AS needle),
  STRUCT('verwaltung' AS id, 'verwaltungswirt' AS needle),
  STRUCT('verwaltung' AS id, 'clerk' AS needle),
  STRUCT('verwaltung' AS id, 'administrativn' AS needle),
  STRUCT('verwaltung' AS id, 'administratief' AS needle),
  STRUCT('kundenservice' AS id, 'kundenservice' AS needle),
  STRUCT('kundenservice' AS id, 'kundenbetreuer' AS needle),
  STRUCT('kundenservice' AS id, 'kundenberater' AS needle),
  STRUCT('kundenservice' AS id, 'customer service' AS needle),
  STRUCT('kundenservice' AS id, 'customer support' AS needle),
  STRUCT('kundenservice' AS id, 'callcenter' AS needle),
  STRUCT('kundenservice' AS id, 'call center' AS needle),
  STRUCT('kundenservice' AS id, 'hotline' AS needle),
  STRUCT('kundenservice' AS id, 'servicemitarbeiter' AS needle),
  STRUCT('kundenservice' AS id, 'kundenzentrum' AS needle),
  STRUCT('kundenservice' AS id, 'helpdesk' AS needle),
  STRUCT('recht' AS id, 'jurist' AS needle),
  STRUCT('recht' AS id, 'rechtsanwalt' AS needle),
  STRUCT('recht' AS id, 'legal counsel' AS needle),
  STRUCT('recht' AS id, 'lawyer' AS needle),
  STRUCT('recht' AS id, 'solicitor' AS needle),
  STRUCT('recht' AS id, 'paralegal' AS needle),
  STRUCT('recht' AS id, 'justiziar' AS needle),
  STRUCT('recht' AS id, 'wirtschaftsjurist' AS needle),
  STRUCT('compliance' AS id, 'compliance' AS needle),
  STRUCT('compliance' AS id, 'datenschutz' AS needle),
  STRUCT('compliance' AS id, 'dsgvo' AS needle),
  STRUCT('compliance' AS id, 'gdpr' AS needle),
  STRUCT('audit' AS id, 'internal audit' AS needle),
  STRUCT('audit' AS id, 'interne revision' AS needle),
  STRUCT('audit' AS id, 'wirtschaftsprüfer' AS needle),
  STRUCT('audit' AS id, 'auditor' AS needle),
  STRUCT('management' AS id, 'geschäftsführer' AS needle),
  STRUCT('management' AS id, 'geschaeftsfuehrer' AS needle),
  STRUCT('management' AS id, 'general manager' AS needle),
  STRUCT('management' AS id, 'betriebsleiter' AS needle),
  STRUCT('management' AS id, 'werksleiter' AS needle),
  STRUCT('management' AS id, 'standortleiter' AS needle),
  STRUCT('management' AS id, 'niederlassungsleiter' AS needle),
  STRUCT('management' AS id, 'managing director' AS needle),
  STRUCT('management' AS id, 'unternehmensführung' AS needle),
  STRUCT('management' AS id, 'unternehmensfuehrung' AS needle),
  STRUCT('management' AS id, 'vorstand' AS needle),
  STRUCT('management' AS id, 'chief executive' AS needle),
  STRUCT('data' AS id, 'data analyst' AS needle),
  STRUCT('data' AS id, 'datenanalyst' AS needle),
  STRUCT('data' AS id, 'data scientist' AS needle),
  STRUCT('data' AS id, 'datenanalystiker' AS needle),
  STRUCT('data' AS id, 'data analytics' AS needle),
  STRUCT('data' AS id, 'reporting analyst' AS needle),
  STRUCT('bi' AS id, 'business intelligence' AS needle),
  STRUCT('bi' AS id, 'power bi' AS needle),
  STRUCT('bi' AS id, 'tableau' AS needle),
  STRUCT('bi' AS id, 'looker' AS needle),
  STRUCT('bi' AS id, 'bi-entwickler' AS needle),
  STRUCT('design' AS id, 'grafikdesigner' AS needle),
  STRUCT('design' AS id, 'graphic design' AS needle),
  STRUCT('design' AS id, 'ux designer' AS needle),
  STRUCT('design' AS id, 'ui designer' AS needle),
  STRUCT('design' AS id, 'mediengestalter' AS needle),
  STRUCT('design' AS id, 'webdesigner' AS needle),
  STRUCT('design' AS id, 'art director' AS needle),
  STRUCT('design' AS id, 'design system' AS needle),
  STRUCT('design' AS id, 'figma' AS needle),
  STRUCT('kommunikation' AS id, 'unternehmenskommunikation' AS needle),
  STRUCT('kommunikation' AS id, 'kommunikation' AS needle),
  STRUCT('kommunikation' AS id, 'content marketing' AS needle),
  STRUCT('kommunikation' AS id, 'social media manager' AS needle),
  STRUCT('pr' AS id, 'public relations' AS needle),
  STRUCT('pr' AS id, 'pressereferent' AS needle),
  STRUCT('pr' AS id, 'pr-manager' AS needle),
  STRUCT('pr' AS id, 'öffentlichkeit' AS needle),
  STRUCT('pr' AS id, 'oeffentlichkeit' AS needle),
  STRUCT('immobilien' AS id, 'immobilien' AS needle),
  STRUCT('immobilien' AS id, 'real estate' AS needle),
  STRUCT('immobilien' AS id, 'property manager' AS needle),
  STRUCT('immobilien' AS id, 'facility manager' AS needle),
  STRUCT('immobilien' AS id, 'hausmeister' AS needle),
  STRUCT('immobilien' AS id, 'immobilienkauf' AS needle),
  STRUCT('immobilien' AS id, 'makler' AS needle),
  STRUCT('immobilien' AS id, 'gebäudemanagement' AS needle),
  STRUCT('immobilien' AS id, 'gebaeudemanagement' AS needle),
  STRUCT('pflege' AS id, 'pflegefach' AS needle),
  STRUCT('pflege' AS id, 'pflegehelfer' AS needle),
  STRUCT('pflege' AS id, 'pflegekraft' AS needle),
  STRUCT('pflege' AS id, 'pflegedienst' AS needle),
  STRUCT('pflege' AS id, 'krankenpflege' AS needle),
  STRUCT('pflege' AS id, 'krankenschwester' AS needle),
  STRUCT('pflege' AS id, 'krankenpfleger' AS needle),
  STRUCT('pflege' AS id, 'altenpflege' AS needle),
  STRUCT('pflege' AS id, 'altenpfleger' AS needle),
  STRUCT('pflege' AS id, 'verpleegkundige' AS needle),
  STRUCT('pflege' AS id, 'verzorgende' AS needle),
  STRUCT('pflege' AS id, 'gesundheits- und kranken' AS needle),
  STRUCT('pflege' AS id, 'wohnbereichsleitung' AS needle),
  STRUCT('pflege' AS id, 'einrichtungsleitung' AS needle),
  STRUCT('pflege' AS id, 'helpende' AS needle),
  STRUCT('pflege' AS id, 'nurse' AS needle),
  STRUCT('pflege' AS id, 'nursing' AS needle),
  STRUCT('pflege' AS id, 'registered nurse' AS needle),
  STRUCT('pflege' AS id, 'hebamme' AS needle),
  STRUCT('medizin' AS id, 'oberarzt' AS needle),
  STRUCT('medizin' AS id, 'assistenzarzt' AS needle),
  STRUCT('medizin' AS id, 'facharzt' AS needle),
  STRUCT('medizin' AS id, 'ärztin' AS needle),
  STRUCT('medizin' AS id, 'arzt' AS needle),
  STRUCT('medizin' AS id, 'physiotherapeut' AS needle),
  STRUCT('medizin' AS id, 'ergotherapeut' AS needle),
  STRUCT('medizin' AS id, 'anästhes' AS needle),
  STRUCT('medizin' AS id, 'anaesthes' AS needle),
  STRUCT('medizin' AS id, 'psychiatrie' AS needle),
  STRUCT('medizin' AS id, 'gynäkolog' AS needle),
  STRUCT('medizin' AS id, 'gynaekolog' AS needle),
  STRUCT('medizin' AS id, 'intensivmedizin' AS needle),
  STRUCT('medizin' AS id, 'medizinische fachangestellte' AS needle),
  STRUCT('medizin' AS id, 'arzthelfer' AS needle),
  STRUCT('gastronomie' AS id, 'koch' AS needle),
  STRUCT('gastronomie' AS id, 'küche' AS needle),
  STRUCT('gastronomie' AS id, 'kueche' AS needle),
  STRUCT('gastronomie' AS id, 'kuchař' AS needle),
  STRUCT('gastronomie' AS id, 'kuchar' AS needle),
  STRUCT('gastronomie' AS id, 'číšník' AS needle),
  STRUCT('gastronomie' AS id, 'cisnik' AS needle),
  STRUCT('gastronomie' AS id, 'servír' AS needle),
  STRUCT('gastronomie' AS id, 'servir' AS needle),
  STRUCT('gastronomie' AS id, 'gastronom' AS needle),
  STRUCT('gastronomie' AS id, 'waiter' AS needle),
  STRUCT('gastronomie' AS id, 'waitress' AS needle),
  STRUCT('gastronomie' AS id, 'werkend kok' AS needle),
  STRUCT('gastronomie' AS id, 'keukenhulp' AS needle),
  STRUCT('gastronomie' AS id, 'metzgerei' AS needle),
  STRUCT('gastronomie' AS id, 'restaurant' AS needle),
  STRUCT('gastronomie' AS id, 'barista' AS needle),
  STRUCT('gastronomie' AS id, 'bäcker' AS needle),
  STRUCT('gastronomie' AS id, 'baecker' AS needle),
  STRUCT('gastronomie' AS id, 'konditor' AS needle),
  STRUCT('gastronomie' AS id, 'občerstvení' AS needle),
  STRUCT('gastronomie' AS id, 'obcerstveni' AS needle),
  STRUCT('gastronomie' AS id, 'commis' AS needle),
  STRUCT('gastronomie' AS id, 'chef de rang' AS needle),
  STRUCT('hotel' AS id, 'hotellerie' AS needle),
  STRUCT('hotel' AS id, 'hotelfach' AS needle),
  STRUCT('hotel' AS id, 'hotelkauf' AS needle),
  STRUCT('hotel' AS id, 'hotelfachmann' AS needle),
  STRUCT('hotel' AS id, 'hotelfachfrau' AS needle),
  STRUCT('hotel' AS id, 'rezeption' AS needle),
  STRUCT('hotel' AS id, 'concierge' AS needle),
  STRUCT('bau' AS id, 'bauhelfer' AS needle),
  STRUCT('bau' AS id, 'baufach' AS needle),
  STRUCT('bau' AS id, 'baustelle' AS needle),
  STRUCT('bau' AS id, 'construction' AS needle),
  STRUCT('bau' AS id, 'výstavby' AS needle),
  STRUCT('bau' AS id, 'vystavby' AS needle),
  STRUCT('bau' AS id, 'dělník' AS needle),
  STRUCT('bau' AS id, 'delnik' AS needle),
  STRUCT('bau' AS id, 'rohbau' AS needle),
  STRUCT('bau' AS id, 'trockenbau' AS needle),
  STRUCT('bau' AS id, 'maurer' AS needle),
  STRUCT('bau' AS id, 'zedník' AS needle),
  STRUCT('bau' AS id, 'zednik' AS needle),
  STRUCT('bau' AS id, 'betonář' AS needle),
  STRUCT('bau' AS id, 'betonar' AS needle),
  STRUCT('bau' AS id, 'gerüstbauer' AS needle),
  STRUCT('bau' AS id, 'geruestbauer' AS needle),
  STRUCT('handwerk' AS id, 'handwerk' AS needle),
  STRUCT('handwerk' AS id, 'zimmermann' AS needle),
  STRUCT('handwerk' AS id, 'timmerman' AS needle),
  STRUCT('handwerk' AS id, 'tischler' AS needle),
  STRUCT('handwerk' AS id, 'zimmerer' AS needle),
  STRUCT('handwerk' AS id, 'maler ' AS needle),
  STRUCT('handwerk' AS id, 'schilder' AS needle),
  STRUCT('handwerk' AS id, 'dachdecker' AS needle),
  STRUCT('handwerk' AS id, 'sanitär' AS needle),
  STRUCT('handwerk' AS id, 'sanitaer' AS needle),
  STRUCT('handwerk' AS id, 'heizung' AS needle),
  STRUCT('handwerk' AS id, 'klempner' AS needle),
  STRUCT('handwerk' AS id, 'schreiner' AS needle),
  STRUCT('handwerk' AS id, 'carpenter' AS needle),
  STRUCT('handwerk' AS id, 'fliesenleger' AS needle),
  STRUCT('handwerk' AS id, 'elektroniker' AS needle),
  STRUCT('handwerk' AS id, 'elektriker' AS needle),
  STRUCT('handwerk' AS id, 'elektrofachkraft' AS needle),
  STRUCT('handwerk' AS id, 'elektroinstallateur' AS needle),
  STRUCT('handwerk' AS id, 'elektromonteur' AS needle),
  STRUCT('handwerk' AS id, 'monteur' AS needle),
  STRUCT('handwerk' AS id, 'metallbauer' AS needle),
  STRUCT('handwerk' AS id, 'servicetechniker' AS needle),
  STRUCT('reinigung' AS id, 'reinigungskraft' AS needle),
  STRUCT('reinigung' AS id, 'reinigung' AS needle),
  STRUCT('reinigung' AS id, 'uklíze' AS needle),
  STRUCT('reinigung' AS id, 'uklize' AS needle),
  STRUCT('reinigung' AS id, 'schoonmaak' AS needle),
  STRUCT('reinigung' AS id, 'schoonmaker' AS needle),
  STRUCT('reinigung' AS id, 'putzhilfe' AS needle),
  STRUCT('reinigung' AS id, 'gebäudereinig' AS needle),
  STRUCT('reinigung' AS id, 'gebaeudereinig' AS needle),
  STRUCT('reinigung' AS id, 'hauswirtschaft' AS needle),
  STRUCT('reinigung' AS id, 'housekeeping' AS needle),
  STRUCT('reinigung' AS id, 'room attendant' AS needle),
  STRUCT('reinigung' AS id, 'cleaner' AS needle),
  STRUCT('erziehung' AS id, 'erzieher' AS needle),
  STRUCT('erziehung' AS id, 'pädagog' AS needle),
  STRUCT('erziehung' AS id, 'padagog' AS needle),
  STRUCT('erziehung' AS id, 'lehrer' AS needle),
  STRUCT('erziehung' AS id, 'teacher' AS needle),
  STRUCT('erziehung' AS id, 'kindergarten' AS needle),
  STRUCT('erziehung' AS id, 'kita ' AS needle),
  STRUCT('erziehung' AS id, 'unterricht' AS needle),
  STRUCT('soziales' AS id, 'sozialarbeiter' AS needle),
  STRUCT('soziales' AS id, 'sozialpädagog' AS needle),
  STRUCT('soziales' AS id, 'sozialpadagog' AS needle),
  STRUCT('soziales' AS id, 'schulsozial' AS needle),
  STRUCT('soziales' AS id, 'sozialassistent' AS needle),
  STRUCT('soziales' AS id, 'heilerziehungspfleger' AS needle),
  STRUCT('soziales' AS id, 'heilerziehung' AS needle),
  STRUCT('soziales' AS id, 'social worker' AS needle),
  STRUCT('sicherheit' AS id, 'security officer' AS needle),
  STRUCT('sicherheit' AS id, 'security guard' AS needle),
  STRUCT('sicherheit' AS id, 'sicherheitsmitarbeiter' AS needle),
  STRUCT('sicherheit' AS id, 'wachdienst' AS needle),
  STRUCT('sicherheit' AS id, 'wachschutz' AS needle),
  STRUCT('sicherheit' AS id, 'werkschutz' AS needle),
  STRUCT('sicherheit' AS id, 'objektschutz' AS needle),
  STRUCT('sicherheit' AS id, 'doorman' AS needle),
  STRUCT('sicherheit' AS id, 'portier' AS needle),
  STRUCT('sicherheit' AS id, 'fluggastsicherheit' AS needle),
  STRUCT('sicherheit' AS id, 'transportation security' AS needle)
]);

CREATE OR REPLACE TABLE `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp`
CLUSTER BY country_iso2, public_rank AS
SELECT
  j.* EXCEPT (specialties),
  IFNULL(s.specialties, ['weitere']) AS specialties
FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country` j
LEFT JOIN (
  SELECT
    j2.job_key,
    ARRAY_AGG(DISTINCT n.id) AS specialties
  FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country` j2
  JOIN `poetic-sentinel-402405.apply_jobs_jobs2_prod.specialty_needles` n
    ON STRPOS(
      LOWER(CONCAT(' ', IFNULL(j2.title, ''), ' ', IFNULL(j2.description_excerpt, ''), ' ')),
      n.needle
    ) > 0
  GROUP BY j2.job_key
) s USING (job_key);

CREATE OR REPLACE TABLE `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country`
CLUSTER BY country_iso2, public_rank AS
SELECT * FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp`;

DROP TABLE `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country_tmp`;

CREATE OR REPLACE TABLE `poetic-sentinel-402405.apply_jobs_jobs2_prod.country_specialty_counts`
PARTITION BY as_of CLUSTER BY country_iso2, specialty AS
SELECT
  CURRENT_DATE() AS as_of,
  country_iso2,
  sp AS specialty,
  COUNTIF(availability = 'available') AS n_available,
  COUNTIF(availability = 'probably_unavailable') AS n_unavailable,
  COUNT(*) AS n_total
FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.job_offers_country`, UNNEST(specialties) AS sp
GROUP BY country_iso2, sp;

SELECT specialty, SUM(n_total) AS n
FROM `poetic-sentinel-402405.apply_jobs_jobs2_prod.country_specialty_counts`
WHERE as_of = CURRENT_DATE()
GROUP BY specialty
ORDER BY n DESC;
