import { expect, test } from "@playwright/test"

test("country select and bar", async ({ page }) => {
  await page.goto("/?view=map")
  await expect(page.getByTestId("country-select")).toBeVisible()
  await expect(page.getByTestId("country-map")).toBeVisible()
  await expect(page.getByTestId("map-progress")).toHaveCount(0, { timeout: 30_000 })
  await expect(page.locator(".leaflet-container")).toBeVisible({ timeout: 30_000 })
  await expect(page.getByTestId("map-stats")).toBeVisible()
  await expect(page.getByTestId("metric-this-month")).toBeVisible()
  await expect(page.getByTestId("country-bar")).toBeVisible()
  await expect(page.getByTestId("country-bar")).not.toContainText("All jobs")
  await expect(page.getByTestId("time-series")).toBeVisible()
  await expect(page.getByTestId("kpi-legend")).toBeVisible()
})

test("map shows a progress bar while the choropleth loads", async ({ page }) => {
  await page.route("**/geo/countries.geojson", async (route) => {
    await new Promise((r) => setTimeout(r, 1200))
    await route.continue()
  })
  await page.goto("/?view=map")
  const progress = page.getByTestId("map-progress")
  await expect(progress).toBeVisible()
  await expect(progress).toContainText("%")
  await expect(progress).toHaveCount(0, { timeout: 30_000 })
  await expect(page.locator(".leaflet-container")).toBeVisible()
})

test("all countries employment on the map", async ({ page }) => {
  await page.goto("/?view=map&country=ALL")
  const select = page.getByTestId("country-select")
  await expect(select).toBeVisible()
  await expect(select).toHaveValue("ALL", { timeout: 20_000 })
  await expect(page.getByTestId("all-countries-option")).toBeAttached()
  await expect(page.getByTestId("country-bar-heading")).toContainText("All countries", { timeout: 25_000 })
  await expect(page.getByTestId("map-stats-country")).toContainText("All countries")
  await expect(page.getByTestId("country-bar").locator('[data-specialty="fertigung"]')).toBeVisible()
  await expect(page.getByTestId("time-series")).toBeVisible()
  await page.getByTestId("catalog-locale-de").click()
  await expect(page.getByTestId("country-bar-heading")).toContainText("Alle Länder")
  await page.getByTestId("catalog-locale-en").click()
  await expect(page.getByTestId("country-bar-heading")).toContainText("All countries")
})

test("occupation labels switch EN DE NL FR", async ({ page }) => {
  await page.goto("/?view=map")
  const bar = page.getByTestId("country-bar")
  await expect(bar).toBeVisible()
  const manufacturing = bar.locator('[data-specialty="fertigung"]')
  await expect(manufacturing).toContainText("Manufacturing")
  await page.getByTestId("catalog-locale-de").click()
  await expect(manufacturing).toContainText("Fertigung")
  await page.getByTestId("catalog-locale-nl").click()
  await expect(manufacturing).toContainText("Fabricage")
  await page.getByTestId("catalog-locale-fr").click()
  await expect(manufacturing).toContainText("Fabrication")
  await page.getByTestId("catalog-locale-en").click()
  await expect(manufacturing).toContainText("Manufacturing")
  await expect(bar.locator('[data-specialty="software"]')).toContainText("Software engineering")
  await expect(bar.locator('[data-specialty="hardware"]')).toContainText("Hardware engineering")
  await expect(bar.locator('[data-specialty="ai"]')).toContainText("Artificial intelligence")
  await expect(bar.locator('[data-specialty="weitere"]')).toHaveCount(0)
})
