export type SkillKind = "hard" | "soft"

export type SkillCluster = {
  id: string
  kind: SkillKind
  names: string[]
  label: string
}

/** Occupational fields used as job categories (multi-label). */
export const SKILL_CATALOG: SkillCluster[] = [
  {
    id: "produktion",
    kind: "hard",
    label: "Produktion und Fertigung",
    names: [
      "produktionsmitarbeiter",
      "produktionshelfer",
      "produktionsfachkraft",
      "produktionstechn",
      "produktions",
      "productiemedewerker",
      "procesoperator",
      "operator",
      "assembler",
      "manufacturing",
      "production worker",
      "production operator",
      "metallhelfer",
      "fertigung",
      "fertigungs",
      "fertigungstechnik",
      "industriemechaniker",
      "maschinen- und anlagenführer",
      "maschinen- und anlagenfuehrer",
      "maschinenbediener",
      "maschinenführer",
      "maschinenfuehrer",
      "anlagenführer",
      "anlagenfuehrer",
      "anlagenbediener",
      "zerspanungsmechaniker",
      "zerspanung",
      "schweißer",
      "schweisser",
      "welder",
      "svářeč",
      "svarovac",
      "schlosser",
      "cnc",
      "dreher",
      "fräser",
      "fraeser",
      "montierer",
      "montagehelfer",
      "mechatroniker",
      "instandhaltung",
      "instandhalter",
      "werkzeugmacher",
      "verfahrenstechnik",
      "werkvoorbereider",
      "elektroniker",
      "elektriker",
      "elektrofachkraft",
      "elektroinstallateur",
      "elektromonteur",
      "monteur",
      "metallbauer",
      "servicetechniker",
    ],
  },
  {
    id: "ingenieurwesen",
    kind: "hard",
    label: "Ingenieurwesen und Forschung",
    names: [
      "ingenieur",
      "engineer",
      "engineering",
      "konstrukteur",
      "konstruktion",
      "entwicklungsingenieur",
      "maschinenbau",
      "bauingenieur",
      "verfahrenstechniker",
      "forschung",
      "forscher",
      "scientist",
      "wissenschaftlicher mitarbeiter",
      "research scientist",
      "r&d",
      "f&e",
      "postdoc",
      "laborant",
      "laboratory",
    ],
  },
  {
    id: "personal",
    kind: "soft",
    label: "Personal",
    names: [
      "personalreferent",
      "personalsachbearbeiter",
      "personalentwicklung",
      "personalleiter",
      "personalfach",
      "personalwesen",
      "human resources",
      "hr manager",
      "hr business",
      "recruiter",
      "recruiting",
      "talent acquisition",
      "payroll",
      "entgeltabrechnung",
      "ausbilder",
    ],
  },
  {
    id: "it",
    kind: "hard",
    label: "IT",
    names: [
      "softwareentwickler",
      "software engineer",
      "software developer",
      "fachinformatiker",
      "informatiker",
      "entwickler",
      "developer",
      "programmer",
      "devops",
      "sysadmin",
      "systemadministrator",
      "it-administrator",
      "it administrator",
      "it-support",
      "it support",
      "it consultant",
      "it-berater",
      "fullstack",
      "full-stack",
      "backend",
      "frontend",
      "javascript",
      "typescript",
      "python",
      "java ",
      "kubernetes",
      "cloud engineer",
      "application manager",
      "sap berat",
      "sap consultant",
      "data engineer",
      "platform engineer",
      "sre",
      "cybersecurity",
      "infosec",
      "appsec",
      "webentwickler",
    ],
  },
  {
    id: "logistik",
    kind: "hard",
    label: "Logistik",
    names: [
      "logistik",
      "lagerist",
      "lagermitarbeiter",
      "lagerhelfer",
      "lagerarbeiter",
      "lagerlogistik",
      "fachkraft für lager",
      "fachkraft fuer lager",
      "kommissionierer",
      "kommissionier",
      "staplerfahrer",
      "gabelstapler",
      "warehouse",
      "supply chain",
      "spedition",
      "disponent",
      "lkw-fahrer",
      "lkw fahrer",
      "kraftfahrer",
      "berufskraftfahrer",
      "lieferfahrer",
      "kurier",
      "lager",
      "logistiek",
      "magazijn",
      "heftruck",
      "vrachtwagen",
      "chauffeur",
      "postbote",
      "paketzustell",
      "skladník",
      "skladnici",
      "skladni",
      "transportarbeiter",
      "versandmitarbeiter",
      "versand",
      "řidič",
      "ridic",
      "taxikář",
      "taxikar",
      "taxi ",
      " taxik",
      "briefträger",
      "brieftraeger",
      "postzustell",
    ],
  },
  {
    id: "qualitaet",
    kind: "hard",
    label: "Qualität",
    names: [
      "qualitätsmanagement",
      "qualitaetsmanagement",
      "qualitätssicherung",
      "qualitaetssicherung",
      "qualitätsprüfer",
      "qualitaetspruefer",
      "quality manager",
      "quality engineer",
      "quality assurance",
      "qmb",
      "iso 9001",
      "qs-mitarbeiter",
      "prüftechniker",
      "prueftechniker",
    ],
  },
  {
    id: "vertrieb",
    kind: "soft",
    label: "Vertrieb, Marketing und Produktmanagement",
    names: [
      "verkäufer",
      "verkaeufer",
      "verkaufer",
      "verkauf",
      "vertrieb",
      "kassierer",
      "kassiertätigkeit",
      "kassiertaetigkeit",
      "einzelhandel",
      "filialleiter",
      "marktleiter",
      "handelsfachwirt",
      "account manager",
      "key account",
      "sales ",
      "inside sales",
      "business development",
      "account executive",
      "verkoop",
      "verkoper",
      "warenverräumung",
      "warenverraeumung",
      "verräumung",
      "warenverräumer",
      "verräumer",
      "prodavač",
      "prodavac",
      "marketing",
      "merchandis",
      "warenpräsentation",
      "warenpraesentation",
      "brand manager",
      "kampagnen",
      "product manager",
      "produktmanager",
      "produktmanagement",
      "product owner",
      "produktowner",
    ],
  },
  {
    id: "projekt",
    kind: "soft",
    label: "Projektmanagement",
    names: [
      "projektleiter",
      "projektmanager",
      "projektkoordinator",
      "project manager",
      "project lead",
      "scrum master",
      "pmo",
      "agile coach",
      "projektmanagement",
      "program manager",
      "projectleider",
    ],
  },
  {
    id: "finanzen",
    kind: "hard",
    label: "Finanzen",
    names: [
      "financial analyst",
      "investment analyst",
      "treasury",
      "finanzanalyst",
      "finanzen",
      "finanzwesen",
      "cfa",
      "mifid",
    ],
  },
  {
    id: "rechnungswesen",
    kind: "hard",
    label: "Rechnungswesen",
    names: [
      "buchhalter",
      "buchhaltung",
      "finanzbuchhalter",
      "bilanzbuchhalter",
      "lohnbuchhalter",
      "rechnungswesen",
      "accountant",
      "steuerfach",
      "wirtschaftsprüf",
      "wirtschaftspruef",
    ],
  },
  {
    id: "controlling",
    kind: "hard",
    label: "Controlling",
    names: ["controlling", "controller", "kostenrechnung"],
  },
  {
    id: "verwaltung",
    kind: "soft",
    label: "Verwaltung",
    names: [
      "verwaltung",
      "sachbearbeiter",
      "office manager",
      "bürokauf",
      "buerokauf",
      "verwaltungsfach",
      "verwaltungsangestellt",
      "sekretär",
      "sekretaer",
      "assistant",
      "assistent",
      "verwaltungswirt",
      "clerk",
      "administrativn",
      "administratief",
    ],
  },
  {
    id: "kundenservice",
    kind: "soft",
    label: "Kundenservice",
    names: [
      "kundenservice",
      "kundenbetreuer",
      "kundenberater",
      "customer service",
      "customer support",
      "callcenter",
      "call center",
      "hotline",
      "servicemitarbeiter",
      "kundenzentrum",
      "helpdesk",
    ],
  },
  {
    id: "recht",
    kind: "hard",
    label: "Recht",
    names: [
      "jurist",
      "rechtsanwalt",
      "legal counsel",
      "lawyer",
      "solicitor",
      "paralegal",
      "justiziar",
      "wirtschaftsjurist",
    ],
  },
  {
    id: "compliance",
    kind: "hard",
    label: "Compliance",
    names: ["compliance", "datenschutz", "dsgvo", "gdpr"],
  },
  {
    id: "audit",
    kind: "hard",
    label: "Audit",
    names: ["internal audit", "interne revision", "wirtschaftsprüfer", "auditor"],
  },
  {
    id: "management",
    kind: "soft",
    label: "Management",
    names: [
      "geschäftsführer",
      "geschaeftsfuehrer",
      "general manager",
      "betriebsleiter",
      "werksleiter",
      "standortleiter",
      "niederlassungsleiter",
      "managing director",
      "unternehmensführung",
      "unternehmensfuehrung",
      "vorstand",
      "chief executive",
    ],
  },
  {
    id: "data",
    kind: "hard",
    label: "Data Analytics",
    names: [
      "data analyst",
      "datenanalyst",
      "data scientist",
      "datenanalystiker",
      "data analytics",
      "reporting analyst",
    ],
  },
  {
    id: "bi",
    kind: "hard",
    label: "Business Intelligence",
    names: ["business intelligence", "power bi", "tableau", "looker", "bi-entwickler"],
  },
  {
    id: "design",
    kind: "soft",
    label: "Design",
    names: [
      "grafikdesigner",
      "graphic design",
      "ux designer",
      "ui designer",
      "mediengestalter",
      "webdesigner",
      "art director",
      "design system",
      "figma",
    ],
  },
  {
    id: "kommunikation",
    kind: "soft",
    label: "Kommunikation",
    names: [
      "unternehmenskommunikation",
      "kommunikation",
      "content marketing",
      "social media manager",
    ],
  },
  {
    id: "pr",
    kind: "soft",
    label: "PR",
    names: ["public relations", "pressereferent", "pr-manager", "öffentlichkeit", "oeffentlichkeit"],
  },
  {
    id: "immobilien",
    kind: "soft",
    label: "Immobilien",
    names: [
      "immobilien",
      "real estate",
      "property manager",
      "facility manager",
      "hausmeister",
      "immobilienkauf",
      "makler",
      "gebäudemanagement",
      "gebaeudemanagement",
    ],
  },
  {
    id: "pflege",
    kind: "hard",
    label: "Pflege",
    names: [
      "pflegefach",
      "pflegehelfer",
      "pflegekraft",
      "pflegedienst",
      "krankenpflege",
      "krankenschwester",
      "krankenpfleger",
      "altenpflege",
      "altenpfleger",
      "verpleegkundige",
      "verzorgende",
      "gesundheits- und kranken",
      "wohnbereichsleitung",
      "einrichtungsleitung",
      "helpende",
      "nurse",
      "nursing",
      "registered nurse",
      "hebamme",
    ],
  },
  {
    id: "medizin",
    kind: "hard",
    label: "Medizin",
    names: [
      "oberarzt",
      "assistenzarzt",
      "facharzt",
      "ärztin",
      "arzt",
      "physiotherapeut",
      "ergotherapeut",
      "anästhes",
      "anaesthes",
      "psychiatrie",
      "gynäkolog",
      "gynaekolog",
      "intensivmedizin",
      "medizinische fachangestellte",
      "arzthelfer",
    ],
  },
  {
    id: "gastronomie",
    kind: "soft",
    label: "Gastronomie",
    names: [
      "koch",
      "küche",
      "kueche",
      "kuchař",
      "kuchar",
      "číšník",
      "cisnik",
      "servír",
      "servir",
      "gastronom",
      "waiter",
      "waitress",
      "werkend kok",
      "keukenhulp",
      "metzgerei",
      "restaurant",
      "barista",
      "bäcker",
      "baecker",
      "konditor",
      "občerstvení",
      "obcerstveni",
      "commis",
      "chef de rang",
    ],
  },
  {
    id: "hotel",
    kind: "soft",
    label: "Hotellerie",
    names: ["hotellerie", "hotelfach", "hotelkauf", "hotelfachmann", "hotelfachfrau", "rezeption", "concierge"],
  },
  {
    id: "bau",
    kind: "hard",
    label: "Bau",
    names: [
      "bauhelfer",
      "baufach",
      "baustelle",
      "construction",
      "výstavby",
      "vystavby",
      "dělník",
      "delnik",
      "rohbau",
      "trockenbau",
      "maurer",
      "zedník",
      "zednik",
      "betonář",
      "betonar",
      "gerüstbauer",
      "geruestbauer",
    ],
  },
  {
    id: "handwerk",
    kind: "hard",
    label: "Handwerk",
    names: [
      "handwerk",
      "zimmermann",
      "timmerman",
      "tischler",
      "zimmerer",
      "maler ",
      "schilder",
      "dachdecker",
      "sanitär",
      "sanitaer",
      "heizung",
      "klempner",
      "schreiner",
      "carpenter",
      "fliesenleger",
    ],
  },
  {
    id: "reinigung",
    kind: "soft",
    label: "Reinigung",
    names: [
      "reinigungskraft",
      "reinigung",
      "uklíze",
      "uklize",
      "schoonmaak",
      "schoonmaker",
      "putzhilfe",
      "gebäudereinig",
      "gebaeudereinig",
      "hauswirtschaft",
      "housekeeping",
      "room attendant",
      "cleaner",
    ],
  },
  {
    id: "erziehung",
    kind: "soft",
    label: "Erziehung",
    names: [
      "erzieher",
      "pädagog",
      "padagog",
      "lehrer",
      "teacher",
      "kindergarten",
      "kita ",
      "unterricht",
    ],
  },
  {
    id: "soziales",
    kind: "soft",
    label: "Soziales",
    names: [
      "sozialarbeiter",
      "sozialpädagog",
      "sozialpadagog",
      "schulsozial",
      "sozialassistent",
      "heilerziehungspfleger",
      "heilerziehung",
      "social worker",
    ],
  },
  {
    id: "sicherheit",
    kind: "soft",
    label: "Sicherheit",
    names: [
      "security officer",
      "security guard",
      "sicherheitsmitarbeiter",
      "wachdienst",
      "wachschutz",
      "werkschutz",
      "objektschutz",
      "doorman",
      "portier",
      "fluggastsicherheit",
      "transportation security",
    ],
  },
  {
    id: "weitere",
    kind: "soft",
    label: "Weitere",
    names: [],
  },
]

export const UNCATEGORIZED_ID = "weitere"

export function extractSpecialties(text: string): string[] {
  const hay = ` ${String(text || "").toLowerCase()} `
  const out: string[] = []
  const seen = new Set<string>()
  for (const sk of SKILL_CATALOG) {
    if (sk.id === "weitere") continue
    if (sk.names.some((n) => hay.includes(n.toLowerCase()))) {
      if (!seen.has(sk.id)) {
        seen.add(sk.id)
        out.push(sk.id)
      }
    }
  }
  if (out.length === 0) return ["weitere"]
  return out
}

export function clusterById(id: string | null | undefined): SkillCluster | undefined {
  if (!id) return undefined
  return SKILL_CATALOG.find((s) => s.id === id)
}

const LABEL_ALIASES: Record<string, string> = {
  uncategorized: "Weitere",
  fertigung: "Produktion und Fertigung",
  forschung: "Ingenieurwesen und Forschung",
  marketing: "Vertrieb, Marketing und Produktmanagement",
  produkt: "Vertrieb, Marketing und Produktmanagement",
}

export function specialtyLabel(id: string): string {
  return LABEL_ALIASES[id] || clusterById(id)?.label || id
}

export function specialtyNeedles(): { id: string; needle: string }[] {
  const out: { id: string; needle: string }[] = []
  for (const sk of SKILL_CATALOG) {
    if (sk.id === "weitere") continue
    for (const n of sk.names) out.push({ id: sk.id, needle: n.toLowerCase() })
  }
  return out
}
