import { foldText } from "./fold"
import { DEFAULT_CATALOG_LOCALE, L, type CatalogLocale, type LocaleLabels } from "./locales"

export type SkillKind = "hard" | "soft"

export type SkillCluster = {
  id: string
  kind: SkillKind
  names: string[]
  label: string
}

/** Occupational fields used as job categories (multi-label). */
export const SKILL_CATALOG: SkillCluster[] = [
  {
    id: "produktion",
    kind: "hard",
    label: "Production",
    names: [
      "produktionsmitarbeiter",
      "produktionshelfer",
      "produktionsfachkraft",
      "produktionstechn",
      "produktions",
      "productiemedewerker",
      "procesoperator",
      "operator",
      "assembler",
      "manufacturing",
      "production worker",
      "production operator",
      "produktion",
      "productie",
      "assemblagemedewerker",
      "metallhelfer",
      "operator vyroby",
      "vyroby",
      "vyrobe",
      "vyrobu",
      "pomocni delnici ve vyrobe",
      "delnici ve vyrobe",
      "ostatni pomocni pracovnici ve vyrobe",
    ],
  },
  {
    id: "fertigung",
    kind: "hard",
    label: "Manufacturing",
    names: [
      "fertigung",
      "fertigungs",
      "fertigungstechnik",
      "industriemechaniker",
      "maschinen- und anlagenführer",
      "maschinen- und anlagenfuehrer",
      "maschinenbediener",
      "maschinenführer",
      "maschinenfuehrer",
      "anlagenführer",
      "anlagenfuehrer",
      "anlagenbediener",
      "zerspanungsmechaniker",
      "zerspanung",
      "schweißer",
      "schweisser",
      "welder",
      "lasser",
      "svářeč",
      "svarovac",
      "schlosser",
      "schleifer",
      "brusic",
      "brusič",
      "metallbearbeitung",
      "obsluha stroju",
      "obsluha stroj",
      "stroju na",
      "zpracovani vyrobku",
      "etiketovan",
      "schaltschrank",
      "cnc",
      "dreher",
      "fräser",
      "fraeser",
      "werkzeugmacher",
      "verfahrenstechnik",
      "werkvoorbereider",
      "loter",
      "metallbearbeiter",
      "karosseriebauer",
      "karosserie",
      "maschineneinrichter",
      "zamecnik",
      "obrabec",
      "strojni obrabec",
    ],
  },
  {
    id: "instandhaltung",
    kind: "hard",
    label: "Maintenance",
    names: [
      "instandhaltung",
      "instandhalter",
      "mechatroniker",
      "montierer",
      "montagehelfer",
      "elektroniker",
      "elektriker",
      "elektrofachkraft",
      "elektroinstallateur",
      "elektromonteur",
      "monteur",
      "metallbauer",
      "servicetechniker",
      "montagemitarbeiter",
      "montagemedewerker",
      "montagehelfer",
      "kfz-mechaniker",
      "kfz mechaniker",
      "kfz-werkstatt",
      "kfz meister",
      "kfz - meister",
      "reifenwechsel",
      "pneuservis",
      "elektrikar",
      "elettricista",
      "automaticien",
      "technicien de maintenance",
      "technische dienst",
      "servicetechniker",
      "messtechniker",
      "montazni",
      "mechanik",
      "mechanic",
      "tecnico meccanico",
    ],
  },
  {
    id: "ingenieurwesen",
    kind: "hard",
    label: "Engineering",
    names: [
      "ingenieur",
      "engineer",
      "engineering",
      "konstrukteur",
      "konstruktion",
      "entwicklungsingenieur",
      "maschinenbau",
      "bauingenieur",
      "verfahrenstechniker",
      "ingenieur",
      "cad tekenaar",
      "tekenaar",
      "elektrotechnik",
    ],
  },
  {
    id: "forschung",
    kind: "hard",
    label: "Research",
    names: [
      "forschung",
      "forscher",
      "scientist",
      "wissenschaftlicher mitarbeiter",
      "research scientist",
      "r&d",
      "f&e",
      "postdoc",
      "laborant",
      "laboratory",
    ],
  },
  {
    id: "personal",
    kind: "soft",
    label: "Human resources",
    names: [
      "personalreferent",
      "personalsachbearbeiter",
      "personalentwicklung",
      "personalleiter",
      "personalfach",
      "personalwesen",
      "human resources",
      "hr manager",
      "hr business",
      "recruiter",
      "recruiting",
      "talent acquisition",
      "payroll",
      "entgeltabrechnung",
      "ausbilder",
    ],
  },
  {
    id: "it",
    kind: "hard",
    label: "IT",
    names: [
      "softwareentwickler",
      "software engineer",
      "software developer",
      "fachinformatiker",
      "informatiker",
      "entwickler",
      "developer",
      "programmer",
      "devops",
      "sysadmin",
      "systemadministrator",
      "it-administrator",
      "it administrator",
      "it-support",
      "it support",
      "it consultant",
      "it-berater",
      "fullstack",
      "full-stack",
      "backend",
      "frontend",
      "javascript",
      "typescript",
      "python",
      "java ",
      "kubernetes",
      "cloud engineer",
      "application manager",
      "sap berat",
      "sap consultant",
      "data engineer",
      "platform engineer",
      "sre",
      "cybersecurity",
      "information security",
      "soc analyst",
      "infosec",
      "appsec",
      "webentwickler",
      "systembeheerder",
      "ict ",
    ],
  },
  {
    id: "software",
    kind: "hard",
    label: "Software engineering",
    names: [
      "software engineer",
      "software engineering",
      "softwareentwickler",
      "software entwickler",
      "software developer",
      "softwareentwick",
      "softwareontwikkelaar",
      "applicatieontwikkelaar",
      "programmeur",
      "programmer",
      "programmierer",
      "programator",
      "vyvojar",
      "vyvojari",
      "fullstack",
      "full-stack",
      "full stack",
      "backend",
      "frontend",
      "webentwickler",
      "web developer",
      "mobile developer",
      "ios developer",
      "android developer",
      "developpeur",
      "développeur",
      "ingenieur logiciel",
      "software",
    ],
  },
  {
    id: "hardware",
    kind: "hard",
    label: "Hardware engineering",
    names: [
      "hardware engineer",
      "hardware engineering",
      "hardwareentwick",
      "hardware entwickler",
      "hardware design",
      "fpga",
      "asic",
      "verilog",
      "vhdl",
      "pcb ",
      "printed circuit",
      "chip design",
      "semiconductor",
      "rtl design",
      "analog design",
      "digital design",
      "ic design",
      "elektronikentwick",
      "embedded hardware",
      "hardware",
    ],
  },
  {
    id: "ai",
    kind: "hard",
    label: "Artificial intelligence",
    names: [
      "artificial intelligence",
      "kunstliche intelligenz",
      "kuenstliche intelligenz",
      "kunstmatige intelligentie",
      "intelligence artificielle",
      "machine learning",
      "maschinelles lernen",
      "deep learning",
      "neural network",
      " ai engineer",
      "ai-engineer",
      "ml engineer",
      "mlops",
      "llm ",
      "generative ai",
      "genai",
      "computer vision",
      "natural language processing",
      "prompt engineer",
      "ki-ingenieur",
      "ki ingenieur",
      "data scientist",
    ],
  },
  {
    id: "logistik",
    kind: "hard",
    label: "Logistics",
    names: [
      "logistik",
      "logistiek",
      "supply chain",
      "spedition",
      "disponent",
      "versandmitarbeiter",
      "versand",
      "transportarbeiter",
    ],
  },
  {
    id: "lager",
    kind: "hard",
    label: "Warehouse",
    names: [
      "lagerist",
      "lagermitarbeiter",
      "lagerhelfer",
      "lagerarbeiter",
      "lagerlogistik",
      "fachkraft für lager",
      "fachkraft fuer lager",
      "kommissionierer",
      "kommissionier",
      "staplerfahrer",
      "gabelstapler",
      "warehouse",
      "lager",
      "magazijn",
      "heftruck",
      "skladnik",
      "skladnici",
      "skladni",
      "vysokozdviz",
      "manipulacnich voziku",
      "verpacker",
      "pakker",
      "obsluha manipula",
      "balici",
      "baliči",
      "etiketovac",
      "plnic",
      "plniči",
    ],
  },
  {
    id: "transport",
    kind: "hard",
    label: "Transport",
    names: [
      "lkw-fahrer",
      "lkw fahrer",
      "kraftfahrer",
      "berufskraftfahrer",
      "lieferfahrer",
      "kurier",
      "vrachtwagen",
      "chauffeur",
      "postbote",
      "paketzustell",
      "řidič",
      "ridic",
      "taxikář",
      "taxikar",
      "taxi ",
      " taxik",
      "briefträger",
      "brieftraeger",
      "postzustell",
      "ridici",
      "vrachtwagenchauffeur",
      "busfahrer",
      "bus chauffeur",
      "fahrer",
      "auslieferungsfahrer",
      "zusteller",
      "bezorger",
      "conducteur",
      "vodici",
      "vodic",
    ],
  },
  {
    id: "qualitaet",
    kind: "hard",
    label: "Quality",
    names: [
      "qualitätsmanagement",
      "qualitaetsmanagement",
      "qualitätssicherung",
      "qualitaetssicherung",
      "qualitätsprüfer",
      "qualitaetspruefer",
      "quality manager",
      "quality engineer",
      "quality assurance",
      "qmb",
      "iso 9001",
      "qs-mitarbeiter",
      "prüftechniker",
      "prueftechniker",
    ],
  },
  {
    id: "vertrieb",
    kind: "soft",
    label: "Sales",
    names: [
      "vertrieb",
      "accountmanager",
      "account manager",
      "obchodni zastupce",
      "obchodni",
      "binnendienst",
      "commercieel",
      "key account",
      "sales ",
      "agente di commercio",
      "inside sales",
      "business development",
      "account executive",
      "handelsfachwirt",
    ],
  },
  {
    id: "einzelhandel",
    kind: "soft",
    label: "Retail",
    names: [
      "verkäufer",
      "verkaeufer",
      "verkaufer",
      "verkauf",
      "kassierer",
      "kassiertätigkeit",
      "kassiertaetigkeit",
      "einzelhandel",
      "filialleiter",
      "marktleiter",
      "verkoop",
      "verkoper",
      "warenverräumung",
      "warenverraeumung",
      "verräumung",
      "warenverräumer",
      "verräumer",
      "prodavač",
      "prodavac",
      "filialleitung",
      "store manager",
      "winkelmedewerker",
      "winkelbediende",
      "supermarkt",
      "kasse",
      "frischetheke",
      "getranke",
      "getränke",
      "backwaren",
      "abholservice",
      "cerpaci stanice",
      "čerpací",
    ],
  },
  {
    id: "marketing",
    kind: "soft",
    label: "Marketing",
    names: [
      "marketing",
      "merchandis",
      "warenpräsentation",
      "warenpraesentation",
      "brand manager",
      "kampagnen",
    ],
  },
  {
    id: "produkt",
    kind: "soft",
    label: "Product management",
    names: [
      "product manager",
      "produktmanager",
      "produktmanagement",
      "product owner",
      "produktowner",
    ],
  },
  {
    id: "projekt",
    kind: "soft",
    label: "Project management",
    names: [
      "projektleiter",
      "projektmanager",
      "projektkoordinator",
      "project manager",
      "project lead",
      "scrum master",
      "pmo",
      "agile coach",
      "projektmanagement",
      "program manager",
      "projectleider",
    ],
  },
  {
    id: "finanzen",
    kind: "hard",
    label: "Finance",
    names: [
      "financial analyst",
      "investment analyst",
      "treasury",
      "finanzanalyst",
      "finanzen",
      "finanzwesen",
      "cfa",
      "mifid",
      "financieel",
      "belastingadviseur",
      "paraplanner",
      "finance manager",
      "finance business",
      "finance partner",
    ],
  },
  {
    id: "rechnungswesen",
    kind: "hard",
    label: "Accounting",
    names: [
      "buchhalter",
      "buchhaltung",
      "finanzbuchhalter",
      "bilanzbuchhalter",
      "lohnbuchhalter",
      "rechnungswesen",
      "accountant",
      "steuerfach",
      "wirtschaftsprüf",
      "wirtschaftspruef",
      "ucetni",
      "boekhouder",
      "comptable",
      "salarisadministrateur",
    ],
  },
  {
    id: "controlling",
    kind: "hard",
    label: "Controlling",
    names: ["controlling", "controller", "kostenrechnung"],
  },
  {
    id: "verwaltung",
    kind: "soft",
    label: "Administration",
    names: [
      "verwaltung",
      "sachbearbeiter",
      "office manager",
      "bürokauf",
      "buerokauf",
      "verwaltungsfach",
      "verwaltungsangestellt",
      "sekretär",
      "sekretaer",
      "assistant",
      "assistent",
      "verwaltungswirt",
      "clerk",
      "administrativn",
      "administratief",
    ],
  },
  {
    id: "kundenservice",
    kind: "soft",
    label: "Customer service",
    names: [
      "kundenservice",
      "kundenbetreuer",
      "kundenberater",
      "customer service",
      "customer support",
      "callcenter",
      "call center",
      "hotline",
      "servicemitarbeiter",
      "kundenzentrum",
      "helpdesk",
      "klantenservice",
    ],
  },
  {
    id: "recht",
    kind: "hard",
    label: "Legal",
    names: [
      "jurist",
      "rechtsanwalt",
      "legal counsel",
      "lawyer",
      "solicitor",
      "paralegal",
      "justiziar",
      "wirtschaftsjurist",
    ],
  },
  {
    id: "compliance",
    kind: "hard",
    label: "Compliance",
    names: ["compliance", "datenschutz", "dsgvo", "gdpr"],
  },
  {
    id: "audit",
    kind: "hard",
    label: "Audit",
    names: ["internal audit", "interne revision", "wirtschaftsprüfer", "auditor"],
  },
  {
    id: "management",
    kind: "soft",
    label: "Management",
    names: [
      "geschäftsführer",
      "geschaeftsfuehrer",
      "general manager",
      "betriebsleiter",
      "werksleiter",
      "standortleiter",
      "niederlassungsleiter",
      "managing director",
      "unternehmensführung",
      "unternehmensfuehrung",
      "vorstand",
      "chief executive",
      "teamleider",
      "leidinggevende",
      "vedouci",
      "bedrijfsleider",
      "team leader",
      "abteilungsleiter",
    ],
  },
  {
    id: "data",
    kind: "hard",
    label: "Data analytics",
    names: [
      "data analyst",
      "datenanalyst",
      "data scientist",
      "datenanalystiker",
      "data analytics",
      "reporting analyst",
    ],
  },
  {
    id: "bi",
    kind: "hard",
    label: "Business intelligence",
    names: ["business intelligence", "power bi", "tableau", "looker", "bi-entwickler"],
  },
  {
    id: "design",
    kind: "soft",
    label: "Design",
    names: [
      "grafikdesigner",
      "graphic design",
      "ux designer",
      "ui designer",
      "mediengestalter",
      "webdesigner",
      "art director",
      "design system",
      "figma",
    ],
  },
  {
    id: "kommunikation",
    kind: "soft",
    label: "Communications",
    names: [
      "unternehmenskommunikation",
      "kommunikation",
      "content marketing",
      "social media manager",
    ],
  },
  {
    id: "pr",
    kind: "soft",
    label: "PR",
    names: ["public relations", "pressereferent", "pr-manager", "öffentlichkeit", "oeffentlichkeit"],
  },
  {
    id: "immobilien",
    kind: "soft",
    label: "Real estate",
    names: [
      "immobilien",
      "real estate",
      "property manager",
      "facility manager",
      "hausmeister",
      "immobilienkauf",
      "makler",
      "gebäudemanagement",
      "gebaeudemanagement",
    ],
  },
  {
    id: "pflege",
    kind: "hard",
    label: "Nursing",
    names: [
      "pflegefach",
      "pflegehelfer",
      "pflegekraft",
      "pflegedienst",
      "krankenpflege",
      "krankenschwester",
      "krankenpfleger",
      "altenpflege",
      "altenpfleger",
      "verpleegkundige",
      "verzorgende",
      "gesundheits- und kranken",
      "wohnbereichsleitung",
      "einrichtungsleitung",
      "helpende",
      "nurse",
      "nursing",
      "registered nurse",
      "hebamme",
      "pflegehilf",
      "sestra",
      "vseobecna sestra",
      "osetrovatel",
      "pfleger",
      "pflege",
      "sanitater",
      "sanitäter",
      "notfallsanitater",
      "notfallsanitäter",
      "intensivpfleger",
      "op-pfleger",
      "dialysepfleger",
    ],
  },
  {
    id: "medizin",
    kind: "hard",
    label: "Medicine",
    names: [
      "oberarzt",
      "assistenzarzt",
      "facharzt",
      "ärztin",
      "arzt",
      "physiotherapeut",
      "ergotherapeut",
      "anästhes",
      "anaesthes",
      "psychiatrie",
      "gynäkolog",
      "gynaekolog",
      "intensivmedizin",
      "medizinische fachangestellte",
      "arzthelfer",
      "internist",
      "lekar",
      "dokter",
      "medecin",
      "physician",
      "psychiater",
      "psycholoog",
      "tandarts",
      "augenoptik",
      "dialyse",
    ],
  },
  {
    id: "gastronomie",
    kind: "soft",
    label: "Food service",
    names: [
      "koch",
      "küche",
      "kueche",
      "kuchař",
      "kuchar",
      "číšník",
      "cisnik",
      "servír",
      "servir",
      "gastronom",
      "waiter",
      "waitress",
      "werkend kok",
      "keukenhulp",
      "metzgerei",
      "restaurant",
      "barista",
      "bäcker",
      "baecker",
      "konditor",
      "občerstvení",
      "obcerstveni",
      "commis",
      "chef de rang",
      "kuchyni",
      "pomocnici v kuchyni",
      "keukenhulp",
      "horeca",
      "kok ",
      "pizzar",
      "pizzař",
      "barman",
      "barmani",
      "convenience",
      "verzehrfertig",
      "speisen",
    ],
  },
  {
    id: "hotel",
    kind: "soft",
    label: "Hotels",
    names: [
      "hotellerie",
      "hotelfach",
      "hotelkauf",
      "hotelfachmann",
      "hotelfachfrau",
      "rezeption",
      "concierge",
      "recepcni",
      "receptionist",
      "receptie",
      "pokojska",
      "pokojská",
      "housekeeping",
    ],
  },
  {
    id: "bau",
    kind: "hard",
    label: "Construction",
    names: [
      "bauhelfer",
      "baufach",
      "baustelle",
      "construction",
      "výstavby",
      "vystavby",
      "dělník",
      "delnik",
      "rohbau",
      "trockenbau",
      "maurer",
      "zedník",
      "zednik",
      "betonář",
      "betonar",
      "gerüstbauer",
      "geruestbauer",
      "uitvoerder",
      "grondwerker",
      "stavebni",
      "calculator",
      "kranfuehrer",
      "kranführer",
      "baggerfahrer",
      "baugeratefuhrer",
      "baugeräteführer",
      "radlader",
      "zednici",
      "staveb",
      "kraanmachinist",
      "tegelzetter",
      "montovanych staveb",
    ],
  },
  {
    id: "handwerk",
    kind: "hard",
    label: "Skilled trades",
    names: [
      "handwerk",
      "zimmermann",
      "timmerman",
      "tischler",
      "zimmerer",
      "maler ",
      "schilder",
      "dachdecker",
      "sanitär",
      "sanitaer",
      "heizung",
      "klempner",
      "schreiner",
      "carpenter",
      "fliesenleger",
      "loodgieter",
      "meubelmaker",
      "schaltschrankbauer",
    ],
  },
  {
    id: "reinigung",
    kind: "soft",
    label: "Cleaning",
    names: [
      "reinigungskraft",
      "reinigung",
      "uklíze",
      "uklize",
      "schoonmaak",
      "schoonmaker",
      "putzhilfe",
      "gebäudereinig",
      "gebaeudereinig",
      "hauswirtschaft",
      "housekeeping",
      "room attendant",
      "cleaner",
      "huishoudelijke",
      "industriereiniger",
      "uklidu",
      "uklid",
      "puhastusteenindaja",
    ],
  },
  {
    id: "erziehung",
    kind: "soft",
    label: "Education",
    names: [
      "erzieher",
      "pädagog",
      "padagog",
      "lehrer",
      "teacher",
      "kindergarten",
      "kita ",
      "unterricht",
      "ucitel",
      "docent",
      "pedagog",
      "asistent pedagoga",
      "detske skupine",
      "leerkracht",
      "schulbegleitung",
      "schulbegleiter",
      "basisonderwijs",
    ],
  },
  {
    id: "soziales",
    kind: "soft",
    label: "Social work",
    names: [
      "sozialarbeiter",
      "sozialpädagog",
      "sozialpadagog",
      "schulsozial",
      "sozialassistent",
      "heilerziehungspfleger",
      "heilerziehung",
      "social worker",
      "begeleider",
      "betreuungskraft",
      "pedagogisch medewerker",
      "socialni",
      "betreutes wohnen",
      "suchtkranke",
    ],
  },
  {
    id: "sicherheit",
    kind: "soft",
    label: "Security",
    names: [
      "security officer",
      "security guard",
      "sicherheitsmitarbeiter",
      "wachdienst",
      "wachschutz",
      "werkschutz",
      "objektschutz",
      "doorman",
      "portier",
      "fluggastsicherheit",
      "transportation security",
      "sicherheits",
      "beveiliger",
      "strazny",
      "ostrahy",
      "securitate",
      "security officer",
      "security guard",
    ],
  },
  {
    id: "beauty",
    kind: "soft",
    label: "Beauty",
    names: [
      "maser",
      "maserka",
      "massage",
      "maniker",
      "pediker",
      "kosmetik",
      "friseur",
      "kapper",
      "hairdresser",
      "beautician",
      "nehtova",
      "kadernik",
      "kadeřník",
      "kadernici",
      "kozmetik",
      "kozmetici",
    ],
  },
  {
    id: "garten",
    kind: "hard",
    label: "Landscaping",
    names: [
      "hovenier",
      "gartner",
      "gaertner",
      "landscap",
      "tuinman",
      "greenkeeper",
      "landschaft",
      "groenvoorziening",
    ],
  },
  {
    id: "general",
    kind: "soft",
    label: "General labor",
    names: [
      "aushilfe",
      "minijob",
      "geringfugig",
      "hilfskraft",
      "aushilfs",
      "pomocnik",
      "pomocni",
      "pomocna",
      "general labor",
      "general labour",
      "unskilled",
      "helfer",
      "minijobber",
      "delnici",
      "dělníci",
    ],
  },
  {
    id: "weitere",
    kind: "soft",
    label: "Other",
    names: [],
  },
]

export const UNCATEGORIZED_ID = "weitere"

export function extractSpecialties(text: string): string[] {
  const hay = ` ${foldText(text || "")} `
  const out: string[] = []
  const seen = new Set<string>()
  for (const sk of SKILL_CATALOG) {
    if (sk.id === "weitere") continue
    if (sk.names.some((n) => hay.includes(foldText(n)))) {
      if (!seen.has(sk.id)) {
        seen.add(sk.id)
        out.push(sk.id)
      }
    }
  }
  if (out.length === 0) return String(text || "").trim() ? ["general"] : ["weitere"]
  return out
}

export function clusterById(id: string | null | undefined): SkillCluster | undefined {
  if (!id) return undefined
  return SKILL_CATALOG.find((s) => s.id === id)
}

export {
  CATALOG_LOCALES,
  DEFAULT_CATALOG_LOCALE,
  CATALOG_LOCALE_STORAGE_KEY,
  isCatalogLocale,
  type CatalogLocale,
} from "./locales"

const SPECIALTY_LABELS: Record<string, LocaleLabels> = {
  produktion: L("Production", "Produktion", "Productie", "Production", "Výroba", "生産", "Tootmine", "Производство"),
  fertigung: L("Manufacturing", "Fertigung", "Fabricage", "Fabrication", "Výroba", "製造", "Tootmine", "Обрабатывающая промышленность"),
  instandhaltung: L("Maintenance", "Instandhaltung", "Onderhoud", "Maintenance", "Údržba", "保全", "Hooldus", "Обслуживание"),
  ingenieurwesen: L("Engineering", "Ingenieurwesen", "Techniek", "Ingénierie", "Inženýrství", "エンジニアリング", "Inseneritöö", "Инженерия"),
  forschung: L("Research", "Forschung", "Onderzoek", "Recherche", "Výzkum", "研究", "Teadus", "Исследования"),
  personal: L("Human resources", "Personal", "Personeel", "Ressources humaines", "Lidské zdroje", "人事", "Personal", "Кадры"),
  it: L("IT", "IT", "IT", "IT", "IT", "IT", "IT", "ИТ"),
  software: L("Software engineering", "Softwareentwicklung", "Software engineering", "Ingénierie logicielle", "Softwarové inženýrství", "ソフトウェアエンジニアリング", "Tarkvaratehnika", "Программная инженерия"),
  hardware: L("Hardware engineering", "Hardwareentwicklung", "Hardware engineering", "Ingénierie matérielle", "Hardwarové inženýrství", "ハードウェアエンジニアリング", "Riistvaratehnika", "Аппаратная инженерия"),
  ai: L("Artificial intelligence", "Künstliche Intelligenz", "Kunstmatige intelligentie", "Intelligence artificielle", "Umělá inteligence", "人工知能", "Tehisintellekt", "Искусственный интеллект"),
  logistik: L("Logistics", "Logistik", "Logistiek", "Logistique", "Logistika", "物流", "Logistika", "Логистика"),
  lager: L("Warehouse", "Lager", "Magazijn", "Entrepôt", "Sklad", "倉庫", "Ladu", "Склад"),
  transport: L("Transport", "Transport", "Transport", "Transport", "Doprava", "輸送", "Transport", "Транспорт"),
  qualitaet: L("Quality", "Qualität", "Kwaliteit", "Qualité", "Kvalita", "品質", "Kvaliteet", "Качество"),
  vertrieb: L("Sales", "Vertrieb", "Verkoop", "Ventes", "Prodej", "営業", "Müük", "Продажи"),
  einzelhandel: L("Retail", "Einzelhandel", "Detailhandel", "Commerce de détail", "Maloobchod", "小売", "Jaekaubandus", "Розничная торговля"),
  marketing: L("Marketing", "Marketing", "Marketing", "Marketing", "Marketing", "マーケティング", "Turundus", "Маркетинг"),
  produkt: L("Product management", "Produktmanagement", "Productmanagement", "Gestion de produit", "Produktový management", "プロダクトマネジメント", "Tootejuhtimine", "Продуктовый менеджмент"),
  projekt: L("Project management", "Projektmanagement", "Projectmanagement", "Gestion de projet", "Projektové řízení", "プロジェクトマネジメント", "Projektijuhtimine", "Управление проектами"),
  finanzen: L("Finance", "Finanzen", "Financiën", "Finance", "Finance", "財務", "Rahandus", "Финансы"),
  rechnungswesen: L("Accounting", "Rechnungswesen", "Boekhouding", "Comptabilité", "Účetnictví", "会計", "Raamatupidamine", "Бухгалтерия"),
  controlling: L("Controlling", "Controlling", "Controlling", "Contrôle de gestion", "Controlling", "管理会計", "Kontrolling", "Контроллинг"),
  verwaltung: L("Administration", "Verwaltung", "Administratie", "Administration", "Administrativa", "総務", "Administreerimine", "Администрация"),
  kundenservice: L("Customer service", "Kundenservice", "Klantenservice", "Service client", "Zákaznický servis", "カスタマーサービス", "Klienditeenindus", "Клиентский сервис"),
  recht: L("Legal", "Recht", "Juridisch", "Droit", "Právo", "法務", "Õigus", "Юриспруденция"),
  compliance: L("Compliance", "Compliance", "Compliance", "Conformité", "Compliance", "コンプライアンス", "Vastavus", "Комплаенс"),
  audit: L("Audit", "Audit", "Audit", "Audit", "Audit", "監査", "Audit", "Аудит"),
  management: L("Management", "Management", "Management", "Management", "Management", "マネジメント", "Juhtimine", "Менеджмент"),
  data: L("Data analytics", "Data Analytics", "Data-analyse", "Analyse de données", "Datová analytika", "データ分析", "Andmeanalüüs", "Аналитика данных"),
  bi: L("Business intelligence", "Business Intelligence", "Business intelligence", "Business intelligence", "Business intelligence", "ビジネスインテリジェンス", "Ärianalüütika", "Бизнес-аналитика"),
  design: L("Design", "Design", "Design", "Design", "Design", "デザイン", "Disain", "Дизайн"),
  kommunikation: L("Communications", "Kommunikation", "Communicatie", "Communication", "Komunikace", "コミュニケーション", "Kommunikatsioon", "Коммуникации"),
  pr: L("PR", "PR", "PR", "RP", "PR", "広報", "PR", "PR"),
  immobilien: L("Real estate", "Immobilien", "Vastgoed", "Immobilier", "Nemovitosti", "不動産", "Kinnisvara", "Недвижимость"),
  pflege: L("Nursing", "Pflege", "Verpleging", "Soins infirmiers", "Ošetřovatelství", "看護", "Õendus", "Сестринское дело"),
  medizin: L("Medicine", "Medizin", "Geneeskunde", "Médecine", "Medicína", "医療", "Meditsiin", "Медицина"),
  gastronomie: L("Food service", "Gastronomie", "Horeca", "Restauration", "Gastronomie", "飲食", "Toitlustus", "Общепит"),
  hotel: L("Hotels", "Hotellerie", "Hotellerie", "Hôtellerie", "Hotelnictví", "ホテル", "Hotellid", "Гостиницы"),
  bau: L("Construction", "Bau", "Bouw", "BTP", "Stavebnictví", "建設", "Ehitus", "Строительство"),
  handwerk: L("Skilled trades", "Handwerk", "Ambacht", "Artisanat", "Řemesla", "技能職", "Käsitöö", "Ремесла"),
  reinigung: L("Cleaning", "Reinigung", "Schoonmaak", "Nettoyage", "Úklid", "清掃", "Koristus", "Уборка"),
  erziehung: L("Education", "Erziehung", "Onderwijs", "Éducation", "Vzdělávání", "教育", "Haridus", "Образование"),
  soziales: L("Social work", "Soziales", "Sociaal werk", "Travail social", "Sociální práce", "ソーシャルワーク", "Sotsiaaltöö", "Социальная работа"),
  sicherheit: L("Security", "Sicherheit", "Beveiliging", "Sécurité", "Bezpečnost", "セキュリティ", "Turvalisus", "Безопасность"),
  beauty: L("Beauty", "Beauty", "Schoonheid", "Beauté", "Krása", "美容", "Ilu", "Красота"),
  garten: L("Landscaping", "Gartenbau", "Hovenier", "Paysagisme", "Zahradnictví", "造園", "Maastikukujundus", "Озеленение"),
  general: L("General labor", "Aushilfe", "Algemeen werk", "Travail général", "Pomocné práce", "一般作業", "Üldtöö", "Подсобные работы"),
  weitere: L("Other", "Weitere", "Overig", "Autre", "Ostatní", "その他", "Muu", "Прочее"),
  uncategorized: L("Other", "Weitere", "Overig", "Autre", "Ostatní", "その他", "Muu", "Прочее"),
}

export function specialtyLabel(id: string, locale: CatalogLocale = DEFAULT_CATALOG_LOCALE): string {
  const row = SPECIALTY_LABELS[id]
  if (row) return row[locale] || row.en
  return clusterById(id)?.label || id
}

export function specialtyNeedles(): { id: string; needle: string }[] {
  const out: { id: string; needle: string }[] = []
  for (const sk of SKILL_CATALOG) {
    if (sk.id === "weitere") continue
    for (const n of sk.names) out.push({ id: sk.id, needle: n.toLowerCase() })
  }
  return out
}
